/**
 * 配置表预定义[本文件由工具生成]
 */

/** 指引枚举 */
enum IGUIDECD {
    /** 场景切换|所有弹窗关闭 */
    SCENE = 1,
    /** 武将列表界面 */
    GEN_LIST_WND = 2,
    /** 已拥有武将创建完毕 */
    GEN_LIST_CR = 3,
    /** 武将获得动画完毕 */
    GEN_GET_WND = 4,
    /** 武将信息界面 */
    GEN_INFO_WND = 5,
    /** 武将强化切卡 */
    GEN_TAB_UP = 6,
    /** 武将技能切卡 */
    GEN_TAB_SKILL = 7,
    /** 武将宝物切卡 */
    GEN_TAB_TREA = 8,
    /** 武将技能升级界面 */
    GEN_SKILL_WND = 9,
    /** 酒馆主界面 */
    TAV_WND = 10,
    /** 酒馆奖励界面 */
    TAV_AWARD_WND = 11,
    /** 动态按钮菜单 */
    MENU_OTHER = 12,
    /** 挂机菜单 */
    MENU_HANG = 13,
    /** 世界地图菜单 */
    MENU_WORD = 14,
    /** 主城菜单 */
    MENU_CITY = 15,
    /** 战斗菜单 */
    MENU_BATTLE = 16,
    /** 布阵 */
    CAMP_WND = 17,
    /** 锻造主界面 */
    EQUIP_WND = 18,
    /** 锻造装备切卡 */
    EQUIP_TAB_EQ = 19,
    /** 锻造强化切卡 */
    EQUIP_TAB_UP = 20,
    /** 锻造进阶切卡 */
    EQUIP_TAB_GR = 21,
    /** 锻造精练切卡 */
    EQUIP_TAB_WR = 22,
    /** boss主界面 */
    BOSS_WND = 23,
    /** 个人boss切卡 */
    BOSS_TAB_PRI = 24,
    /** 排行boss切卡 */
    BOSS_TAB_RANK = 25,
    /** 世界boss切卡 */
    BOSS_TAB_WOR = 26,
    /** 军备主界面 */
    ARMY_WND = 27,
    /** 军备步兵切卡 */
    ARMY_TAB_BB = 28,
    /** 军备骑兵切卡 */
    ARMY_TAB_QB = 29,
    /** 切换枪兵卡 */
    ARMY_TAB_QIANB = 30,
    /** 军备弓兵切卡 */
    ARMY_TAB_GB = 31,
    /** 练兵 */
    ARMY_TAB_TRAI = 32,
    /** 升阶 */
    ARMY_TAB_UP = 33,
    /** 升級界面 */
    BUILD_LEVEL_WND = 34,
    /** 加速界面 */
    SPEED_WND = 35,
    /** 物资征战主界面 */
    MATERIA_CAMP_WND = 36,
    /** 主城建筑 */
    MAIN_BUILD = 37,
    /** 竞技场 */
    PVP_WND = 38,
    /** 名将副本主界面 */
    QUARTER_WND = 39,
    /** 名将副本详细 */
    QUARTER_INFO_WND = 40,
    /** 挂机战斗初始化 */
    WAR_HANG_INIT = 41,
    /** 战斗开始 */
    WAR_BEGIN = 42,
    /** 战斗结束 */
    WAR_END = 43,
    /** 名将副本 */
    WAR_GEN_INIT = 44,
    /** 世界地图布阵 */
    WORLD_CAMP_WND = 45,
    /** 世界资源 */
    WORLD_RESOURCE = 46,
    /** 采集菜单 */
    MENU_COLLECT = 47,
    /** 事件队伍选择 */
    WORLD_EVT_SEL_WND = 48,
    /** 拜访界面 */
    WORLD_VISIT_WND = 49,
    /** 出征队伍 拜访武将 选择界面 */
    WORLD_FIGHT_SEL_WND = 50,
    /** 新手战斗 */
    GUIDE_WAR_PROCESS = 51,
    /** 解锁面板 */
    WORLD_LOCKED_WND = 52,
    /** 聚宝盆主界面 */
    CORNUCOPIA_WND = 53,
}

