var TASK_UI;
(function (TASK_UI) {
    /**
     * 100000
     * Menu层，如底部操作栏，顶部状态栏等
     * */
    TASK_UI[TASK_UI["MENU_INIT"] = 100001] = "MENU_INIT";
    TASK_UI[TASK_UI["MENU_SHOW"] = 100002] = "MENU_SHOW";
    TASK_UI[TASK_UI["MENU_BATTLE_TOOLSBAR_REFRES"] = 100004] = "MENU_BATTLE_TOOLSBAR_REFRES";
    TASK_UI[TASK_UI["MENU_BATTLE_VIEW"] = 100008] = "MENU_BATTLE_VIEW";
    TASK_UI[TASK_UI["MENU_BATTLE_DESTORY_WALL"] = 100009] = "MENU_BATTLE_DESTORY_WALL";
    // MENU_BATTLE_TOPBAR = 110000,//战斗界面顶部操作栏
    TASK_UI[TASK_UI["MENU_MAIN_TOPBAR"] = 110001] = "MENU_MAIN_TOPBAR";
    TASK_UI[TASK_UI["MENU_MAIN_TOP_OTHER"] = 110002] = "MENU_MAIN_TOP_OTHER";
    TASK_UI[TASK_UI["MENU_MAIN_SCENE"] = 110003] = "MENU_MAIN_SCENE";
    TASK_UI[TASK_UI["MENU_MAIN_HANG"] = 110004] = "MENU_MAIN_HANG";
    TASK_UI[TASK_UI["MENU_MAIN_WORLD"] = 110005] = "MENU_MAIN_WORLD";
    TASK_UI[TASK_UI["MENU_MAIN_CROSS"] = 110006] = "MENU_MAIN_CROSS";
    TASK_UI[TASK_UI["MENU_NOTICE"] = 120000] = "MENU_NOTICE";
    /**
     * 200000
     * Map层，世界地图，战斗地图等
     * */
    TASK_UI[TASK_UI["MAP_BATTLE"] = 200000] = "MAP_BATTLE";
    TASK_UI[TASK_UI["MAP_WORLD"] = 200001] = "MAP_WORLD";
    TASK_UI[TASK_UI["MAP_MAIN"] = 200002] = "MAP_MAIN";
    TASK_UI[TASK_UI["MAP_CROSS_WAR"] = 200003] = "MAP_CROSS_WAR";
    TASK_UI[TASK_UI["MAP_CROSS_WALL_WAR"] = 200004] = "MAP_CROSS_WALL_WAR";
    // MAP_BATTLE_LIST = 200003,//选战场列表（test）
    // MAP_CITY_HITWALL_INFO = 200008,//撞墙榜面板
    TASK_UI[TASK_UI["MAP_NOVICE"] = 200009] = "MAP_NOVICE";
    TASK_UI[TASK_UI["WAIT_BATTLE_MAP"] = 200010] = "WAIT_BATTLE_MAP";
    TASK_UI[TASK_UI["AWAY_FROM_KEYBOARD"] = 200011] = "AWAY_FROM_KEYBOARD";
    TASK_UI[TASK_UI["MAP_MAIN_MOVE"] = 200101] = "MAP_MAIN_MOVE";
    TASK_UI[TASK_UI["MAP_WORLD_MOVE"] = 200102] = "MAP_WORLD_MOVE";
    /**
     * 300000
     * POP弹窗层
     * */
    TASK_UI[TASK_UI["POP_CHAT_MAIN"] = 300000] = "POP_CHAT_MAIN";
    TASK_UI[TASK_UI["POP_CHAT_MAIN_TIPS"] = 300001] = "POP_CHAT_MAIN_TIPS";
    TASK_UI[TASK_UI["POP_MILITARY_EXPLOIT_TASK"] = 300100] = "POP_MILITARY_EXPLOIT_TASK";
    TASK_UI[TASK_UI["POP_MILITARY_EXPLOIT_RANK"] = 300101] = "POP_MILITARY_EXPLOIT_RANK";
    TASK_UI[TASK_UI["POP_MILITARY_EXPLOIT_BOGUA"] = 300102] = "POP_MILITARY_EXPLOIT_BOGUA";
    TASK_UI[TASK_UI["POP_GENERAL_OPEN_INFO_VIEW"] = 300200] = "POP_GENERAL_OPEN_INFO_VIEW";
    TASK_UI[TASK_UI["POP_GENERAL_OPEN_DETAIL_VIEW"] = 300202] = "POP_GENERAL_OPEN_DETAIL_VIEW";
    TASK_UI[TASK_UI["POP_GENERAL_OPEN_UP_SKILL_VIEW"] = 300204] = "POP_GENERAL_OPEN_UP_SKILL_VIEW";
    TASK_UI[TASK_UI["POP_GENERAL_ATTRIBUTE_EFFECT"] = 300205] = "POP_GENERAL_ATTRIBUTE_EFFECT";
    TASK_UI[TASK_UI["POP_GENERAL_GET_VIEW"] = 300206] = "POP_GENERAL_GET_VIEW";
    TASK_UI[TASK_UI["POP_GENERAL_TREA_LIST"] = 300207] = "POP_GENERAL_TREA_LIST";
    TASK_UI[TASK_UI["POP_GENERAL_GET_VIEWII"] = 300208] = "POP_GENERAL_GET_VIEWII";
    TASK_UI[TASK_UI["POP_GENERAL_UPSTAR_VIEWII"] = 300209] = "POP_GENERAL_UPSTAR_VIEWII";
    TASK_UI[TASK_UI["POP_GENERAL_TUPO_VIEW"] = 300210] = "POP_GENERAL_TUPO_VIEW";
    TASK_UI[TASK_UI["POP_GENERAL_UNLOCK_SKILL"] = 300211] = "POP_GENERAL_UNLOCK_SKILL";
    TASK_UI[TASK_UI["POP_GENERAL_UPGRADE_VIEW"] = 300212] = "POP_GENERAL_UPGRADE_VIEW";
    // POP_MAP_EVENT_CONFIRM = 300400,//世界事件确认框
    TASK_UI[TASK_UI["POP_ROLE_INFO_VIEW"] = 300500] = "POP_ROLE_INFO_VIEW";
    TASK_UI[TASK_UI["POP_ROLE_CHANGE_NAME"] = 300501] = "POP_ROLE_CHANGE_NAME";
    TASK_UI[TASK_UI["POP_ROLE_REPLACE_IMG"] = 300502] = "POP_ROLE_REPLACE_IMG";
    TASK_UI[TASK_UI["POP_ROLE_LEVEL_PANEL"] = 300503] = "POP_ROLE_LEVEL_PANEL";
    TASK_UI[TASK_UI["POP_ROLE_GIFT_DH"] = 300504] = "POP_ROLE_GIFT_DH";
    // POP_VERSUS_SEARCH_VIEW = 300600, //对战搜索
    // POP_VERSUS_CHOICE_VIEW = 300601, //对战选择
    // POP_VERSUS_ONBATTLE_VIEW = 300602, //对战上阵
    // POP_VERSUS_REFRESH_OPEN_VIEW = 300603, //对战开启进度
    TASK_UI[TASK_UI["POP_RESULT_BATTLE_VIEW"] = 300700] = "POP_RESULT_BATTLE_VIEW";
    TASK_UI[TASK_UI["POP_RESULT_ARENA_BATTLE_VIEW"] = 300703] = "POP_RESULT_ARENA_BATTLE_VIEW";
    TASK_UI[TASK_UI["POP_RESULT_RAMPART_BATTLE_VIEW"] = 300704] = "POP_RESULT_RAMPART_BATTLE_VIEW";
    TASK_UI[TASK_UI["POP_RESULT_HISTORY_BATTLE_VIEW"] = 300705] = "POP_RESULT_HISTORY_BATTLE_VIEW";
    /**登录 */
    TASK_UI[TASK_UI["POP_LOGIN_SERVER_LIST"] = 310000] = "POP_LOGIN_SERVER_LIST";
    TASK_UI[TASK_UI["POP_LOGIN_CREATE_ROLE_VIEW"] = 310001] = "POP_LOGIN_CREATE_ROLE_VIEW";
    TASK_UI[TASK_UI["POP_LOGIN_SELECT_ROLE_VIEW"] = 310002] = "POP_LOGIN_SELECT_ROLE_VIEW";
    TASK_UI[TASK_UI["POP_LOGIN_NOTICE"] = 310004] = "POP_LOGIN_NOTICE";
    /**主城 */
    TASK_UI[TASK_UI["POP_BUILDING_INFO_VIEW"] = 310101] = "POP_BUILDING_INFO_VIEW";
    // POP_MAP_BUILD_INFO = 310102,
    // POP_NOVICE_BUILD_INFO = 310103,
    TASK_UI[TASK_UI["POP_BUILDING_FUNCITON_MEUN_VIEW"] = 310104] = "POP_BUILDING_FUNCITON_MEUN_VIEW";
    TASK_UI[TASK_UI["POP_BUILDING_MOVE_VIEW"] = 310105] = "POP_BUILDING_MOVE_VIEW";
    TASK_UI[TASK_UI["POP_COM_SPEED_UP_VIEW"] = 310106] = "POP_COM_SPEED_UP_VIEW";
    TASK_UI[TASK_UI["POP_BUILD_LEVEL_UP_VIEW"] = 310107] = "POP_BUILD_LEVEL_UP_VIEW";
    TASK_UI[TASK_UI["POP_ARENA_PANEL"] = 311001] = "POP_ARENA_PANEL";
    TASK_UI[TASK_UI["POP_ARENA_CLEAR_UP_PANEL"] = 311002] = "POP_ARENA_CLEAR_UP_PANEL";
    // POP_DECISIVE_BATTLE = 320000,//决战
    // POP_BIG_HARVEST = 320001,//大丰收
    // POP_VIP_BUY = 320002,//vip
    // POP_WORLD_MAP_THUM = 320003,//世界地图缩略图
    // /**庆典 */
    // POP_CELEBARATION_VIEW = 320101,
    // /**庆典结束奖励 */
    // POP_CELEBARATION_REWARD = 320102,
    // /**庆典分数加成 */
    // POP_CELEBARATION_SCORE = 320103,
    TASK_UI[TASK_UI["POP_TECHNOLOGY_VIEW"] = 322000] = "POP_TECHNOLOGY_VIEW";
    TASK_UI[TASK_UI["POP_TECHNOLOGY_PANEL"] = 322001] = "POP_TECHNOLOGY_PANEL";
    // POP_WARCRAFT_VIEW = 323000,   // 兵法面板
    // POP_WARCRAFT_PANEL = 323001,   // 兵法详情面板
    TASK_UI[TASK_UI["POP_MAIL_LIST_VIEW"] = 324000] = "POP_MAIL_LIST_VIEW";
    TASK_UI[TASK_UI["POP_BAG_LIST_VIEW"] = 324003] = "POP_BAG_LIST_VIEW";
    TASK_UI[TASK_UI["POP_BAG_PANEL"] = 324004] = "POP_BAG_PANEL";
    TASK_UI[TASK_UI["Cornucopai_PANEL"] = 324018] = "Cornucopai_PANEL";
    TASK_UI[TASK_UI["WELFARE_PANEL"] = 324021] = "WELFARE_PANEL";
    TASK_UI[TASK_UI["TASK_ACTIVATION_PANEL"] = 324022] = "TASK_ACTIVATION_PANEL";
    TASK_UI[TASK_UI["PromtDynamic_TEXT_PANEL"] = 324023] = "PromtDynamic_TEXT_PANEL";
    TASK_UI[TASK_UI["TRAIN_SOLDIER_PANEL"] = 324024] = "TRAIN_SOLDIER_PANEL";
    TASK_UI[TASK_UI["LEGION_APPLY_WND"] = 324025] = "LEGION_APPLY_WND";
    TASK_UI[TASK_UI["LEGION_RECORD_WND"] = 324026] = "LEGION_RECORD_WND";
    TASK_UI[TASK_UI["SOLDIER_UPGRADE_PANEL"] = 324029] = "SOLDIER_UPGRADE_PANEL";
    /**pvp */
    TASK_UI[TASK_UI["POP_PVPARENA_PANEL"] = 325001] = "POP_PVPARENA_PANEL";
    TASK_UI[TASK_UI["POP_PVPARENA_RANK_PANEL"] = 325002] = "POP_PVPARENA_RANK_PANEL";
    TASK_UI[TASK_UI["POP_PVPARENA_NOTICE_PANEL"] = 325003] = "POP_PVPARENA_NOTICE_PANEL";
    TASK_UI[TASK_UI["POP_PVPARENA_SHOP_PANEL"] = 325004] = "POP_PVPARENA_SHOP_PANEL";
    TASK_UI[TASK_UI["SHOP_BUY_DLG_PANEL"] = 325005] = "SHOP_BUY_DLG_PANEL";
    /** 珍宝商店面板 */
    TASK_UI[TASK_UI["SHOP_TREASURE_PANEL"] = 326001] = "SHOP_TREASURE_PANEL";
    // SHOP_CLOUD_PANEL = 326002,         //云游商店面板
    TASK_UI[TASK_UI["SHOP_FREE_PANEL"] = 326003] = "SHOP_FREE_PANEL";
    TASK_UI[TASK_UI["SHOP_FREE_SUC_PANEL"] = 326004] = "SHOP_FREE_SUC_PANEL";
    TASK_UI[TASK_UI["SHOP_FREE_RECORD_PANEL"] = 326005] = "SHOP_FREE_RECORD_PANEL";
    /**装备 */
    TASK_UI[TASK_UI["POP_EQUIP_MAIN_WND"] = 327001] = "POP_EQUIP_MAIN_WND";
    TASK_UI[TASK_UI["POP_EQUIP_SEL_WND"] = 327002] = "POP_EQUIP_SEL_WND";
    TASK_UI[TASK_UI["POP_EQUIP_ADD_WND"] = 327003] = "POP_EQUIP_ADD_WND";
    TASK_UI[TASK_UI["POP_EQUIP_WEAR_INFO_WND"] = 327004] = "POP_EQUIP_WEAR_INFO_WND";
    TASK_UI[TASK_UI["POP_EQUIP_RECYCLE"] = 327005] = "POP_EQUIP_RECYCLE";
    /**宝物 */
    TASK_UI[TASK_UI["TREASURE_MAIN"] = 328001] = "TREASURE_MAIN";
    TASK_UI[TASK_UI["TREASURE_INFO"] = 328002] = "TREASURE_INFO";
    TASK_UI[TASK_UI["TREASURE_INLAY"] = 328003] = "TREASURE_INLAY";
    /**联盟 */
    TASK_UI[TASK_UI["LEGION_LIST_WND"] = 329001] = "LEGION_LIST_WND";
    TASK_UI[TASK_UI["LEGION_INFO_PANEL"] = 329002] = "LEGION_INFO_PANEL";
    TASK_UI[TASK_UI["LEGION_MAIN_WND"] = 329003] = "LEGION_MAIN_WND";
    TASK_UI[TASK_UI["LEGION_CREATE_WND"] = 329004] = "LEGION_CREATE_WND";
    TASK_UI[TASK_UI["LEGION_RANK_PANEL"] = 329008] = "LEGION_RANK_PANEL";
    TASK_UI[TASK_UI["LEGION_INVITATE_PANEL"] = 329010] = "LEGION_INVITATE_PANEL";
    TASK_UI[TASK_UI["LEGION_LIST_WND_UPDATE"] = 3290012] = "LEGION_LIST_WND_UPDATE";
    TASK_UI[TASK_UI["LEGION_SET_WND"] = 3290013] = "LEGION_SET_WND";
    TASK_UI[TASK_UI["LEGION_SET_NOTICE_WND"] = 3290014] = "LEGION_SET_NOTICE_WND";
    TASK_UI[TASK_UI["LEGION_APPOINT_WND"] = 3290015] = "LEGION_APPOINT_WND";
    TASK_UI[TASK_UI["LEGION_TECH_WND"] = 3290016] = "LEGION_TECH_WND";
    // POP_BUILD_FIEF_PANEL = 330000,      //封地选择面板
    // POP_BUILD_FIEF_CONSTRU_PANEL = 330001,  //封地建设面板
    // POP_BUILD_FIEF_LIST = 330002,        //封地列表
    // POP_BUILD_GARRET_MAIN = 330003,      //龙腾阁主面板
    // POP_BUILD_GARRET_POPUP = 330004,     //龙腾阁面板弹窗
    TASK_UI[TASK_UI["POP_GUIDE_SELECT_COUNTRY"] = 340000] = "POP_GUIDE_SELECT_COUNTRY";
    // POP_GUIDE_PLOT1 = 340001,//新手开场图文动画1
    // POP_GUIDE_PLOT2 = 340002,//新手开场图文动画2
    TASK_UI[TASK_UI["POP_ACTIVITY_REPEAT"] = 360004] = "POP_ACTIVITY_REPEAT";
    TASK_UI[TASK_UI["POP_ACTIVITY_ONLINE_REWARD"] = 360005] = "POP_ACTIVITY_ONLINE_REWARD";
    TASK_UI[TASK_UI["POP_ACTIVITY_ADD_RECHARGE"] = 360006] = "POP_ACTIVITY_ADD_RECHARGE";
    TASK_UI[TASK_UI["POP_ACTIVITY_SEVEN_DAY"] = 360007] = "POP_ACTIVITY_SEVEN_DAY";
    TASK_UI[TASK_UI["POP_ACTIVITY_BAR_ATK"] = 360008] = "POP_ACTIVITY_BAR_ATK";
    TASK_UI[TASK_UI["POP_ACTIVITY_EMPEROR_ADVANCE"] = 360010] = "POP_ACTIVITY_EMPEROR_ADVANCE";
    TASK_UI[TASK_UI["POP_ACTIVITY_EMPEROR_DETAILS"] = 360011] = "POP_ACTIVITY_EMPEROR_DETAILS";
    TASK_UI[TASK_UI["POP_ACTIVITY_EMPEROR_CITY_INFO"] = 360012] = "POP_ACTIVITY_EMPEROR_CITY_INFO";
    TASK_UI[TASK_UI["POP_ACTIVITY_EMPEROR_CORONATION"] = 360013] = "POP_ACTIVITY_EMPEROR_CORONATION";
    TASK_UI[TASK_UI["POP_ACTIVITY_EMPEROR_RANK"] = 360014] = "POP_ACTIVITY_EMPEROR_RANK";
    TASK_UI[TASK_UI["POP_ACTIVITY_TURNTABLE"] = 360015] = "POP_ACTIVITY_TURNTABLE";
    TASK_UI[TASK_UI["POP_ACTIVITY_SEVENII"] = 360016] = "POP_ACTIVITY_SEVENII";
    TASK_UI[TASK_UI["POP_ACTIVITY_NEWYAER"] = 360017] = "POP_ACTIVITY_NEWYAER";
    TASK_UI[TASK_UI["POP_ACTIVITY_ONE_GIFT_BAG"] = 360009] = "POP_ACTIVITY_ONE_GIFT_BAG";
    TASK_UI[TASK_UI["POP_ACTIVITY_ADD_GIFTBAG"] = 390000] = "POP_ACTIVITY_ADD_GIFTBAG";
    TASK_UI[TASK_UI["POP_ACTIVITY_GIFTBAG_TIP_POP"] = 390001] = "POP_ACTIVITY_GIFTBAG_TIP_POP";
    TASK_UI[TASK_UI["POP_ACTIVITY_ADD_GIFTSHOP"] = 390002] = "POP_ACTIVITY_ADD_GIFTSHOP";
    TASK_UI[TASK_UI["POP_ACTIVITY_NEW_GENERAL"] = 361000] = "POP_ACTIVITY_NEW_GENERAL";
    TASK_UI[TASK_UI["POP_ACTIVITY_SELECT_REWARD"] = 361001] = "POP_ACTIVITY_SELECT_REWARD";
    // POP_TEMPLE_MAIN_PANEL = 370000, //寺庙
    // POP_TANK_OPEN = 380000, //战车
    // POP_TANK_BUY_OPEN = 380001, //战车皮肤购买
    // /**小秘书 */
    // POP_SECRETARY_VIEW = 380100,
    /**功能预告 */
    // POP_FUNCITON_NOTIC_VIEW = 380201,
    /**新功能开启 */
    // POP_FUNCITON_OPEN_VIEW = 380203,
    /**功能预览界面 */
    TASK_UI[TASK_UI["POP_FUNCITON_PREVIEW_VIEW"] = 380205] = "POP_FUNCITON_PREVIEW_VIEW";
    /**新功能弹出界面 */
    TASK_UI[TASK_UI["POP_FUNCITON_NEW_VIEW"] = 380207] = "POP_FUNCITON_NEW_VIEW";
    /**通用奖励面板*/
    TASK_UI[TASK_UI["GET_REWARD_VIEW"] = 380300] = "GET_REWARD_VIEW";
    /**礼包奖励 */
    TASK_UI[TASK_UI["POP_GIFT_BAG_VIEW"] = 390000] = "POP_GIFT_BAG_VIEW";
    /**付费类UI */
    TASK_UI[TASK_UI["POP_PAY_FORTUNE_VIEW"] = 391003] = "POP_PAY_FORTUNE_VIEW";
    TASK_UI[TASK_UI["POP_PAY_First_VIEW"] = 391004] = "POP_PAY_First_VIEW";
    TASK_UI[TASK_UI["POP_PAY_SHOP_VIEW"] = 391005] = "POP_PAY_SHOP_VIEW";
    TASK_UI[TASK_UI["POP_KING_VIEW"] = 391006] = "POP_KING_VIEW";
    TASK_UI[TASK_UI["POP_PAY_SHOP_YU_VIEW"] = 391007] = "POP_PAY_SHOP_YU_VIEW";
    TASK_UI[TASK_UI["POP_DAILY_SURPRISE"] = 391008] = "POP_DAILY_SURPRISE";
    /**世界地图 */
    TASK_UI[TASK_UI["POP_WORLD_HERO_PANEL"] = 392001] = "POP_WORLD_HERO_PANEL";
    TASK_UI[TASK_UI["POP_WORLD_VIEW_PANEL"] = 392002] = "POP_WORLD_VIEW_PANEL";
    TASK_UI[TASK_UI["POP_WORLD_HERO_EVT_PANEL"] = 392003] = "POP_WORLD_HERO_EVT_PANEL";
    TASK_UI[TASK_UI["POP_WORLD_CITY_INFO_PANEL"] = 392004] = "POP_WORLD_CITY_INFO_PANEL";
    TASK_UI[TASK_UI["POP_WORLD_ACCELERATE_PANEL"] = 392005] = "POP_WORLD_ACCELERATE_PANEL";
    TASK_UI[TASK_UI["POP_WORLD_RULE_PANEL"] = 392006] = "POP_WORLD_RULE_PANEL";
    TASK_UI[TASK_UI["POP_WORLD_BATTLE_VIEW"] = 392007] = "POP_WORLD_BATTLE_VIEW";
    TASK_UI[TASK_UI["POP_WORLD_BATTLE_PANEL"] = 392008] = "POP_WORLD_BATTLE_PANEL";
    TASK_UI[TASK_UI["POP_WORLD_THUM_VIEW"] = 392009] = "POP_WORLD_THUM_VIEW";
    TASK_UI[TASK_UI["POP_WORLD_RANK_VIEW"] = 392010] = "POP_WORLD_RANK_VIEW";
    TASK_UI[TASK_UI["POP_WORLD_VISIT_ATTACK"] = 392011] = "POP_WORLD_VISIT_ATTACK";
    TASK_UI[TASK_UI["POP_WORLD_SIEGE_VIEW"] = 392013] = "POP_WORLD_SIEGE_VIEW";
    TASK_UI[TASK_UI["POP_WORLD_SEARCH_VIEW"] = 392014] = "POP_WORLD_SEARCH_VIEW";
    TASK_UI[TASK_UI["POP_WORLD_SIEGE_RESULT"] = 392015] = "POP_WORLD_SIEGE_RESULT";
    TASK_UI[TASK_UI["POP_WORLD_SIEGE_KILL"] = 392016] = "POP_WORLD_SIEGE_KILL";
    TASK_UI[TASK_UI["POP_WORLD_FIRST_OCCUPY_PANEL"] = 392017] = "POP_WORLD_FIRST_OCCUPY_PANEL";
    TASK_UI[TASK_UI["POP_WORLD_MAIN_EXPLOIT_WND"] = 392018] = "POP_WORLD_MAIN_EXPLOIT_WND";
    TASK_UI[TASK_UI["POP_WORLD_LOCK_TASK_PANEL"] = 392019] = "POP_WORLD_LOCK_TASK_PANEL";
    TASK_UI[TASK_UI["POP_WORLD_TROOP_PANEL"] = 392020] = "POP_WORLD_TROOP_PANEL";
    TASK_UI[TASK_UI["POP_WORLD_NEW_OPEN_PANEL"] = 392021] = "POP_WORLD_NEW_OPEN_PANEL";
    TASK_UI[TASK_UI["POP_WORLD_DIALOG_VIEW"] = 392022] = "POP_WORLD_DIALOG_VIEW";
    TASK_UI[TASK_UI["POP_WORLD_CITY_TROOP_PANEL"] = 392023] = "POP_WORLD_CITY_TROOP_PANEL";
    TASK_UI[TASK_UI["POP_WORLD_CITY_BUILDING"] = 392024] = "POP_WORLD_CITY_BUILDING";
    TASK_UI[TASK_UI["POP_WORLD_CITY_BUILD_INFO"] = 392025] = "POP_WORLD_CITY_BUILD_INFO";
    TASK_UI[TASK_UI["POP_WORLD_NOTICE_VIEW"] = 392026] = "POP_WORLD_NOTICE_VIEW";
    /**活动军营上下阵 */
    TASK_UI[TASK_UI["POS_CAMP_VIEW"] = 393001] = "POS_CAMP_VIEW";
    TASK_UI[TASK_UI["POS_PARTRO_VIEW"] = 393002] = "POS_PARTRO_VIEW";
    /**挂机ui */
    TASK_UI[TASK_UI["POS_PATROL_OFFLINE_REWARD_VIEW"] = 394000] = "POS_PATROL_OFFLINE_REWARD_VIEW";
    TASK_UI[TASK_UI["POS_PATROL_SPEED_UP_REWARD_VIEW"] = 394001] = "POS_PATROL_SPEED_UP_REWARD_VIEW";
    TASK_UI[TASK_UI["POS_PATROL_REWARD_CHANGE_VIEW"] = 394002] = "POS_PATROL_REWARD_CHANGE_VIEW";
    TASK_UI[TASK_UI["POS_PATROL_AWARD_VIEW"] = 394003] = "POS_PATROL_AWARD_VIEW";
    TASK_UI[TASK_UI["POS_PATROL_BOSS_VIEW"] = 394004] = "POS_PATROL_BOSS_VIEW";
    TASK_UI[TASK_UI["POS_PATROL_GET_AWARD_VIEW"] = 394005] = "POS_PATROL_GET_AWARD_VIEW";
    /**
     * 400000
     * GUIDE指引层
     * */
    //new ============================
    TASK_UI[TASK_UI["GUIDE_DES_VIEW"] = 400004] = "GUIDE_DES_VIEW";
    TASK_UI[TASK_UI["GUIDE_DIALOG_VIEW"] = 400005] = "GUIDE_DIALOG_VIEW";
    TASK_UI[TASK_UI["GUIDE_TOUCH_VIEW"] = 400006] = "GUIDE_TOUCH_VIEW";
    TASK_UI[TASK_UI["GUIDE_DELAY_MASK_VIEW"] = 400007] = "GUIDE_DELAY_MASK_VIEW";
    TASK_UI[TASK_UI["GUIDE_INTRODUCTION_VIEW"] = 400008] = "GUIDE_INTRODUCTION_VIEW";
    // GUIDE_GRADIENT_VIEW = 400009,//渐变遮罩
    // GUIDE_CITY_BATTLE_PLOT_VIEW = 400010,//主城战斗剧情
    TASK_UI[TASK_UI["GUIDE_TOUCH_TIPS"] = 400011] = "GUIDE_TOUCH_TIPS";
    /**
     * 490000-490099
     * 国家官职系统
     */
    TASK_UI[TASK_UI["COUNTRY_MAIN_PANEL"] = 490000] = "COUNTRY_MAIN_PANEL";
    TASK_UI[TASK_UI["COUNTRY_APPLY_LIST"] = 490001] = "COUNTRY_APPLY_LIST";
    TASK_UI[TASK_UI["COUNTRY_JOB_INFO"] = 490002] = "COUNTRY_JOB_INFO";
    TASK_UI[TASK_UI["COUNTRY_CORONATION_PANEL"] = 49003] = "COUNTRY_CORONATION_PANEL";
    /**
     * 490100-490199
     * 行营系统
     */
    TASK_UI[TASK_UI["HEADQUARTER_MAIN_PANEL"] = 490100] = "HEADQUARTER_MAIN_PANEL";
    TASK_UI[TASK_UI["HEADQUARTER_INFO_PANEL"] = 490101] = "HEADQUARTER_INFO_PANEL";
    /**
     * 490200-490299
     * 酒馆系统
     */
    TASK_UI[TASK_UI["TAVERN_MAIN_PANEL"] = 490200] = "TAVERN_MAIN_PANEL";
    TASK_UI[TASK_UI["TAVERN_INFO_PANEL"] = 490201] = "TAVERN_INFO_PANEL";
    TASK_UI[TASK_UI["TAVERN_BUY_TICK_DLG"] = 490202] = "TAVERN_BUY_TICK_DLG";
    TASK_UI[TASK_UI["TAVERN_CHECK_PANEL"] = 490203] = "TAVERN_CHECK_PANEL";
    TASK_UI[TASK_UI["TAVERN_SAFETY_PANEL"] = 490204] = "TAVERN_SAFETY_PANEL";
    /**
     * 490300-490399
     * 排行榜系统
     */
    TASK_UI[TASK_UI["RANK_MAIN_PANEL"] = 490300] = "RANK_MAIN_PANEL";
    /**
     * 490400-490499
     * boss系统
     */
    TASK_UI[TASK_UI["BOSS_INFO_PANEL"] = 490400] = "BOSS_INFO_PANEL";
    // BOSS_BOX_REWARD = 490401,  //奖励界面
    // BOSS_BUY_QUICK_PANEL = 490402,    //快速购买
    TASK_UI[TASK_UI["BOSS_BOX_RANKREWARD"] = 490403] = "BOSS_BOX_RANKREWARD";
    TASK_UI[TASK_UI["BOSS_HURT_RANK"] = 490404] = "BOSS_HURT_RANK";
    /**
   * 490500-490599
   * 材料副本系统
   */
    TASK_UI[TASK_UI["MATERIAL_INFO_PANEL"] = 490500] = "MATERIAL_INFO_PANEL";
    TASK_UI[TASK_UI["MATERIAL_INFO__BUY_DLG"] = 490501] = "MATERIAL_INFO__BUY_DLG";
    /**
     * 缘分490600-490699
     */
    TASK_UI[TASK_UI["FATE_GENERAL_VIEW"] = 490600] = "FATE_GENERAL_VIEW";
    TASK_UI[TASK_UI["FATE_GENERAL_ACTIVE_VIEW"] = 490601] = "FATE_GENERAL_ACTIVE_VIEW";
    TASK_UI[TASK_UI["FATE_TEAM_VIEW"] = 490602] = "FATE_TEAM_VIEW";
    /**重生490700-490799*/
    TASK_UI[TASK_UI["REBIRTH_WND"] = 490700] = "REBIRTH_WND";
    /**
     * 通用界面
     * 500000
     */
    TASK_UI[TASK_UI["NOR_SOURCE_VIEW_PANEL"] = 500001] = "NOR_SOURCE_VIEW_PANEL";
    TASK_UI[TASK_UI["NOR_BOX_INFO_PANEL"] = 500002] = "NOR_BOX_INFO_PANEL";
    TASK_UI[TASK_UI["NOR_REWARD__PANEL"] = 500003] = "NOR_REWARD__PANEL";
    TASK_UI[TASK_UI["PLAYER_INFO_PANEL"] = 500004] = "PLAYER_INFO_PANEL";
    TASK_UI[TASK_UI["PLAYER_SPEEDY_BUY_PANEL"] = 500005] = "PLAYER_SPEEDY_BUY_PANEL";
    TASK_UI[TASK_UI["PLAYER_LEVEL_UP_VIEW"] = 500006] = "PLAYER_LEVEL_UP_VIEW";
    TASK_UI[TASK_UI["NOR_EQUIP_FULL_VIEW"] = 500007] = "NOR_EQUIP_FULL_VIEW";
    TASK_UI[TASK_UI["COM_HELP_DOC"] = 500008] = "COM_HELP_DOC";
    TASK_UI[TASK_UI["COM_ACT_NOTICE"] = 500009] = "COM_ACT_NOTICE";
    TASK_UI[TASK_UI["NOR_FIGHT_VIEW"] = 500010] = "NOR_FIGHT_VIEW";
    TASK_UI[TASK_UI["LEGION_INFO_CHECK_VIEW"] = 500011] = "LEGION_INFO_CHECK_VIEW";
    TASK_UI[TASK_UI["GENERAL_INFO_CHECK_VIEW"] = 500012] = "GENERAL_INFO_CHECK_VIEW";
    TASK_UI[TASK_UI["COM_BUY_ITEM_WND"] = 500013] = "COM_BUY_ITEM_WND";
    TASK_UI[TASK_UI["TIP_CHECK_ITEM_INFO"] = 5000014] = "TIP_CHECK_ITEM_INFO";
    TASK_UI[TASK_UI["SERVICE_VIP"] = 5000015] = "SERVICE_VIP";
    /**
     * vip界面
     */
    TASK_UI[TASK_UI["VIP_MAIN_PANEL"] = 510000] = "VIP_MAIN_PANEL";
    /**
     * 700000
     * OTHER
     * */
    /** 军备 */
    TASK_UI[TASK_UI["ARMS_PANEL"] = 520000] = "ARMS_PANEL";
    /** 膜拜界面 */
    TASK_UI[TASK_UI["WORSHIP_PANEL"] = 530000] = "WORSHIP_PANEL";
    /**
    * 540000-540000
    * 行营系统
    */
    TASK_UI[TASK_UI["HISTORYWAR_MAIN_PANEL"] = 540000] = "HISTORYWAR_MAIN_PANEL";
    TASK_UI[TASK_UI["HISTORYWAR_INFO_PANEL"] = 540001] = "HISTORYWAR_INFO_PANEL";
    /**
     * 550000 跨服战系统
     */
    TASK_UI[TASK_UI["CROSS_SERVER_TEAM_PANEL"] = 550000] = "CROSS_SERVER_TEAM_PANEL";
    TASK_UI[TASK_UI["CROSS_SERVER_DETAIL_VIEW"] = 550001] = "CROSS_SERVER_DETAIL_VIEW";
    TASK_UI[TASK_UI["CROSS_SERVER_SAND_TABLE"] = 550002] = "CROSS_SERVER_SAND_TABLE";
    TASK_UI[TASK_UI["CRSOS_SERVER_WAR_SITUTION"] = 550003] = "CRSOS_SERVER_WAR_SITUTION";
    TASK_UI[TASK_UI["CROSS_SERVER_CITY_TIPS"] = 550004] = "CROSS_SERVER_CITY_TIPS";
    TASK_UI[TASK_UI["CROSS_SERVER_BUFF"] = 550005] = "CROSS_SERVER_BUFF";
    TASK_UI[TASK_UI["CROSS_SERVER_RANK"] = 550006] = "CROSS_SERVER_RANK";
    TASK_UI[TASK_UI["CRSOS_SERVER_LEGION_UI"] = 550007] = "CRSOS_SERVER_LEGION_UI";
    TASK_UI[TASK_UI["CROSS_BARRACKS"] = 550008] = "CROSS_BARRACKS";
    TASK_UI[TASK_UI["CROSS_HERO_PANEL"] = 550009] = "CROSS_HERO_PANEL";
    TASK_UI[TASK_UI["CROSS_BUY_TOWER_PANEL"] = 550010] = "CROSS_BUY_TOWER_PANEL";
    TASK_UI[TASK_UI["CROSS_RESULT_VIEW"] = 550011] = "CROSS_RESULT_VIEW";
})(TASK_UI || (TASK_UI = {}));
var TestNav;
(function (TestNav) {
    TestNav[TestNav["TEST_ANIM"] = 1000000] = "TEST_ANIM";
    TestNav[TestNav["TEST_CREATE_LANCER"] = 1000001] = "TEST_CREATE_LANCER";
    TestNav[TestNav["TEST_CREATE_CATAPULT"] = 1000002] = "TEST_CREATE_CATAPULT";
    TestNav[TestNav["TEST_CREATE_ARCHER"] = 1000003] = "TEST_CREATE_ARCHER";
    TestNav[TestNav["TEST_CLEAN"] = 1000004] = "TEST_CLEAN";
    TestNav[TestNav["TEST_CHANGE_STATUS"] = 1000005] = "TEST_CHANGE_STATUS";
    TestNav[TestNav["TEST_ANIM_SCALE"] = 1000006] = "TEST_ANIM_SCALE";
    TestNav[TestNav["TEST_CHANGE_DIR"] = 1000007] = "TEST_CHANGE_DIR";
    TestNav[TestNav["TEST_CREATE_KNIGHT"] = 1000008] = "TEST_CREATE_KNIGHT";
    TestNav[TestNav["TEST_CREATE_EFFECT"] = 1000009] = "TEST_CREATE_EFFECT";
    TestNav[TestNav["TEST_CREATE_TYPE"] = 1000010] = "TEST_CREATE_TYPE";
    TestNav[TestNav["TEST_CREATE_HOPLITE"] = 1000011] = "TEST_CREATE_HOPLITE";
    TestNav[TestNav["TEST_CREATE_SQUARE"] = 1000012] = "TEST_CREATE_SQUARE";
    TestNav[TestNav["TEST_START_SKILL"] = 1000013] = "TEST_START_SKILL";
    TestNav[TestNav["TEST_IS_CREATER_SOLDIER"] = 2000001] = "TEST_IS_CREATER_SOLDIER";
    TestNav[TestNav["TEST_WAR"] = 2000002] = "TEST_WAR";
    TestNav[TestNav["TEST_SETTING"] = 2000003] = "TEST_SETTING";
    TestNav[TestNav["TEST_RGB"] = 2000004] = "TEST_RGB";
})(TestNav || (TestNav = {}));
