/**
 * 配置表预定义[本文件由工具生成]
 */

/** CLEnum */
enum CLEnum {
    /** ￥98买基金 */
    AC_BUY_98 = 7,
    /** 月卡周卡 */
    AC_CARD = 8,
    /** 最多选择四个 */
    AC_CHOICE_FOUR = 9,
    /** 请选择物品 */
    AC_CHOICE_ITEM = 10,
    /** <font color=#abb7d1>进度</font> */
    AC_CO_PROGRESS = 11,
    /** 活动倒计时： */
    AC_COUNT_TIME = 12,
    /** 单笔充值 */
    AC_DANBI = 13,
    /** 每日活动 */
    AC_DAY_TITLE = 14,
    /** 已完成 */
    AC_FINISH = 15,
    /** 免费 */
    AC_FREE = 16,
    /** 第%s天 */
    AC_GET_DAY = 17,
    /** %s天后开启 */
    AC_GET_DAY_AFTER = 18,
    /** 领取失败 */
    AC_GET_FAL = 19,
    /** 获得物品id:%s */
    AC_GET_ITEM = 20,
    /** 已失效 */
    AC_GET_SX = 21,
    /** 成长基金 */
    AC_GROW = 22,
    /** 发放 */
    AC_HAND_OUT = 23,
    /** 所属：%s */
    AC_KING_BLONG = 24,
    /** 1、开服第三天开始进行封王战活动，玩家可以分别攻打成都、洛阳、建业三座王城。\n\n2、攻下王城的该场战斗中，战功第一的玩家获得王位。\n\n3、失去王城则失去王位。再次获得任一王城则可夺回王位。 */
    AC_KING_DES = 25,
    /** <font color=#abb7d1>君王论：</font>管理国家\n<font color=#abb7d1>百官朝拜：</font>统治所有国家官职\n<font color=#abb7d1>帝王之师：</font>武力智力统帅+<font color=#00ff00>2</font>\n */
    AC_KING_PC = 26,
    /** 称王特权 */
    AC_KING_PT = 27,
    /** <font color=#abb7d1>丰饶：</font>每个城池的太守可以获得税收收入\n<font color=#abb7d1>金玉成堆：</font>税收可获得以下资源 */
    AC_KING_SC = 28,
    /** <font color=#70f145>蜀国</font> */
    AC_KING_SHU = 29,
    /** 分封 */
    AC_KING_ST = 30,
    /** 活动剩余时间<font color=#FFFFFF>%s</font> */
    AC_KING_STOP_TIME = 31,
    /** 开启剩余时间  <font color=#FFFFFF>%s</font> */
    AC_KING_TIME = 32,
    /** 封王战 */
    AC_KING_TITLE = 33,
    /** <font color=#44d0f3>魏国</font> */
    AC_KING_WEI = 34,
    /** <font color=#FF3F3F>吴国</font> */
    AC_KING_WU = 35,
    /** <font color=#e9e9e6>中立</font> */
    AC_KING_ZL = 36,
    /** 每日登录 */
    AC_LOGIN_DAIDY = 37,
    /** 公告 */
    AC_NOTICE = 38,
    /** ￥%s抢购 */
    AC_ONE_BAG_TIP = 39,
    /** 消费豪礼 */
    AC_PAY_ALL = 40,
    /** 首充60元宝 */
    AC_PAY_FIRST = 41,
    /** 单充%s元宝 */
    AC_PAY_FIRST_COT = 42,
    /** 前往充值 */
    AC_PAY_GOTO = 43,
    /** 进度 */
    AC_PROGRESS = 44,
    /** 直购礼包 */
    AC_PURCHGE_BAG = 45,
    /** %s名以外 */
    AC_RANK_OUTSIDE = 46,
    /** 你目前排名： */
    AC_RANK_TIP = 47,
    /** 充值 */
    AC_RE = 48,
    /** 累计充值 */
    AC_RECHARGE_ALL = 49,
    /** 续费 */
    AC_RENEW = 50,
    /** 查看贵族特权 */
    AC_SEE_VIP = 51,
    /** 第一天 */
    AC_SEVEN_DAY1 = 52,
    /** 第二天 */
    AC_SEVEN_DAY2 = 53,
    /** 第三天 */
    AC_SEVEN_DAY3 = 54,
    /** 第四天 */
    AC_SEVEN_DAY4 = 55,
    /** 第五天 */
    AC_SEVEN_DAY5 = 56,
    /** 第六天 */
    AC_SEVEN_DAY6 = 57,
    /** 第七天 */
    AC_SEVEN_DAY7 = 58,
    /** <font color=#abb7d1>限购</font> <font color=#e9e9e9>%s/%s</font> */
    AC_SHOP_LIMIT = 59,
    /** %s天 */
    AC_SIGN_DAY = 60,
    /** 全勤  */
    AC_SIGN_FULL = 61,
    /** 签到 */
    AC_SIGN_UP = 62,
    /** 贵%s双倍 */
    AC_SIGN_VIP = 63,
    /** 开始 */
    AC_START = 64,
    /** 可补签 */
    AC_SUP_SIGN = 65,
    /** 剩余%s天 */
    AC_SUR_DAY = 66,
    /** 精彩活动 */
    AC_TITLE = 67,
    /** 转盘 */
    AC_TUR = 68,
    /** 活动未开启 */
    AC_UNOPEN = 69,
    /** ￥%s */
    AC_Y = 70,
    /** 操作过于频繁！ */
    ACTION_FAST = 71,
    /** 同意 */
    AGREED = 72,
    /** 竞技场 */
    ARENA = 73,
    /** 未上榜 */
    ARENA_NONE = 74,
    /** 主公,您的挑战次数不足 */
    ARENA_NUM_FAL = 75,
    /** 是否花费[img]icon_source_gold_png[/img]<font color = #e9e9e6>%s元宝</font>购买次数？ */
    ARENA_NUM_TIPS = 76,
    /** 竞技排行 */
    ARENA_RANK = 77,
    /** 战报 */
    ARENA_RECORD = 78,
    /** 刷新 */
    ARENA_SX = 79,
    /** %s天前 */
    ARENA_TIME = 80,
    /** %s小时前 */
    ARENA_TIME1 = 81,
    /** %s分钟前 */
    ARENA_TIME2 = 82,
    /** 部队 */
    ARMY = 83,
    /** 刀兵 */
    ARMY_BB = 84,
    /** 弓兵 */
    ARMY_GB = 85,
    /** 进阶等级不能超过兵营10级 */
    ARMY_GRADE_FAL = 86,
    /** 当前兵种需解锁建筑【%s】 */
    ARMY_OPEN = 87,
    /** 枪兵 */
    ARMY_QB = 88,
    /** 骑兵 */
    ARMY_QIB = 89,
    /** 升阶 */
    ARMY_TAB_SJ = 90,
    /** 招募 */
    ARMY_TAB_ZM = 91,
    /** 士兵训练中 */
    ARMY_TRAIN = 92,
    /** 兵力已满，提升兵营等级可提高兵力上限 */
    ARMY_ZM_FAL = 93,
    /** 请选择训练数量 */
    ARMY_ZM_FAL1 = 94,
    /** 是否花费[img]icon_source_gold_png[/img]<font color = #e9e9e6>%s元宝</font>立刻完成招募？ */
    ARMY_ZM_TIPS = 95,
    /** 攻击 */
    ATTACK = 96,
    /** 攻击+%s */
    ATTACK_ADD = 97,
    /** 物品 */
    BAG = 98,
    /** 购买成功 */
    BAG_BUY_SUC = 99,
    /** 获得物品<font color = #00ff00>%s</font>%s */
    BAG_GET_TIPS = 100,
    /** 虎睛石 */
    BAG_ITEM_HQS = 101,
    /** 尖晶石 */
    BAG_ITEM_JJS = 102,
    /** 绿松石 */
    BAG_ITEM_LSS = 103,
    /** 青金石 */
    BAG_ITEM_QJS = 104,
    /** 日光石 */
    BAG_ITEM_RGS = 105,
    /** 苏纪石 */
    BAG_ITEM_SJS = 106,
    /** 月长石 */
    BAG_ITEM_YCS = 107,
    /** 来源 */
    BAG_SOURCE = 108,
    /** 全部 */
    BAG_TAB_ALL = 109,
    /** 宝物碎片 */
    BAG_TAB_BWSP = 110,
    /** 技能碎片 */
    BAG_TAB_JNSP = 111,
    /** 加速 */
    BAG_TAB_JS = 112,
    /** 碎片 */
    BAG_TAB_SP = 113,
    /** 武将碎片 */
    BAG_TAB_WJSP = 114,
    /** 消耗品 */
    BAG_TAB_XHP = 115,
    /** 资源 */
    BAG_TAB_ZY = 116,
    /** 宝石 */
    BAG_TAB_BS = 117,
    /** 没有足够的%s！ */
    BAG_TIPS_DJSL = 118,
    /** 使用 */
    BAG_USE = 119,
    /** 物品数量为0 */
    BAG_USE_FAL = 120,
    /** 黄巾攻城 */
    BAR_TITLE = 121,
    /** 剩余购买挑战次数不足 */
    BOSS_BUY_FAL = 122,
    /** 每周一 */
    BOSS_DAY1 = 123,
    /** 每周二 */
    BOSS_DAY2 = 124,
    /** 每周三 */
    BOSS_DAY3 = 125,
    /** 每周四 */
    BOSS_DAY4 = 126,
    /** 每周五 */
    BOSS_DAY5 = 127,
    /** 每周六 */
    BOSS_DAY6 = 128,
    /** 每周日 */
    BOSS_DAY7 = 129,
    /** 您的挑战次数已满 */
    BOSS_FIGHT_FULL = 130,
    /** 伤害榜单 */
    BOSS_HURT_RANK = 131,
    /** 获得了1次挑战机会 */
    BOSS_NUM_TIPS = 132,
    /** 百战精华不足 */
    BOSS_SCORE = 133,
    /** 个人 */
    BOSS_TAB_GR = 134,
    /** 排名 */
    BOSS_TAB_PM = 135,
    /** 世界 */
    BOSS_TAB_SJ = 136,
    /** 血战群雄 */
    BOSS_TITLE = 137,
    /** 宝箱奖励 */
    BOX_AWARD = 138,
    /** 购买 */
    BUY = 139,
    /** 已购买 */
    BUY_ALR = 140,
    /** 购买并使用 */
    BUY_AND_USE = 141,
    /** 免费购买 */
    BUY_FREE = 142,
    /** 立即购买 */
    BUY_NOW = 143,
    /** 购买数量不能为0 */
    BUY_NUM_FAL = 144,
    /** 确认购买 */
    BUY_SURE = 145,
    /** 布阵 */
    CAMP = 146,
    /** 部队 */
    CAMP_ARMY = 147,
    /** 内政部队 */
    CAMP_ARMY1 = 148,
    /** 是否返回出生城 */
    CAMP_BIRTH_TIPS = 149,
    /** 非空闲状态部队，不能更改队伍 */
    CAMP_FAL = 150,
    /** 没有可上阵武将 */
    CAMP_FAL1 = 151,
    /** 当前阵型没有修改 */
    CAMP_FAL2 = 152,
    /** 武将已上阵 */
    CAMP_FAL3 = 153,
    /** 该部队已满员 */
    CAMP_FAL4 = 154,
    /** 挑战 */
    CAMP_FIGHT = 155,
    /** 挑战中 */
    CAMP_FIGHT1 = 156,
    /** 情缘名字 */
    CAMP_NAME_QY = 157,
    /** 未编队 */
    CAMP_NONE = 158,
    /** 一键上阵 */
    CAMP_ON_KEY = 159,
    /** 重置 */
    CAMP_RESET = 160,
    /** 保存 */
    CAMP_SAVE = 161,
    /** 阵型更新成功 */
    CAMP_SUC = 162,
    /** 扫荡 */
    CAMP_SWEEP = 163,
    /** 请先布阵 */
    CAMP_TIPS = 164,
    /** 部队已离开%s，请将部队返回后再试 */
    CAMP_TIPS1 = 165,
    /** 取消 */
    CANCEL = 166,
    /** 过关斩将 */
    CHALL = 167,
    /** 闯关 */
    CHALL_FIGHT = 168,
    /** 最少挑战到第七关即可扫荡 */
    CHALL_FIGHT_FAL3 = 169,
    /** 第 %s 关 */
    CHALL_NUM = 170,
    /** 擂台重置 */
    CHALL_RESET = 171,
    /** 没有需要重置的擂台 */
    CHALL_RESET_FAL = 172,
    /** 重置需要%s元宝, 当前元宝不足%s */
    CHALL_RESET_FAL1 = 173,
    /** 没有可扫荡的擂台 */
    CHALL_RESET_FAL2 = 174,
    /** 确认使用%s元宝，重置擂台吗？ */
    CHALL_RESET_SURE = 175,
    /** 解除屏蔽 */
    CHAT_BLACK_CANCEL = 176,
    /** 解除屏蔽成功！ */
    CHAT_BLACK_DEL = 177,
    /** 黑名单已满，请先清理黑名单! */
    CHAT_BLACK_FUL = 178,
    /** 黑名单人数：<font color = #e9e9e6>%s/%s</font> */
    CHAT_BLACK_NUM = 179,
    /** 玩家<font color = #00ff00>【%s】</font>添加到屏蔽列表！ */
    CHAT_BLACK_SUC = 180,
    /** 加入黑名单后,该玩家在聊天频道发言不会显示 */
    CHAT_BLACK_TIPS = 181,
    /** 国家 */
    CHAT_COUNTRY = 182,
    /** 请输入内容 */
    CHAT_INPUT_TIPS = 183,
    /** 操作过于频繁！ */
    CHAT_INVATE_FAL = 184,
    /** 联盟 */
    CHAT_LEGION = 185,
    /** 未加入联盟前不能在联盟频道发言 */
    CHAT_LEGION_FAIL = 186,
    /** 尚未加入联盟！ */
    CHAT_LEGION_FAIL2 = 187,
    /** 前往加入联盟 */
    CHAT_LEGION_GO = 188,
    /** 发送聊天消息，需要玩家达到%s级 */
    CHAT_LIMI_LEVEL = 189,
    /** 请输入内容 */
    CHAT_LIMI_SEND = 190,
    /** 消息长度超过50字！ */
    CHAT_LIMI_SEND2 = 191,
    /** 该玩家在黑名单中！ */
    CHAT_LIMI_SEND3 = 192,
    /** 不能私聊自己！ */
    CHAT_LIMI_SEND4 = 193,
    /** %s频道发言至少需要%s秒间隔 */
    CHAT_LIMI_SEND5 = 194,
    /** 盟 */
    CHAT_MLEGION = 195,
    /** 私 */
    CHAT_MPRI = 196,
    /** 邀请【%s】加入联盟【%s】 */
    CHAT_MSG_INVATE = 197,
    /** 【%s】邀请您加入联盟【%s】 */
    CHAT_MSG_INVATE2 = 198,
    /** 私聊 */
    CHAT_MSG_PRI = 199,
    /** 刚刚 */
    CHAT_MSG_TIME = 200,
    /** 国 */
    CHAT_MSTATE = 201,
    /** 没有私聊对象！ */
    CHAT_PRI_FAL = 202,
    /** 与<font color = #e9e9e6>%s</font>的聊天 */
    CHAT_PRI_TO = 203,
    /** 私人 */
    CHAT_PRIVATE = 204,
    /** 今天不能再举报！ */
    CHAT_REPORT_FAL = 205,
    /** 您已举报，请等待审核！ */
    CHAT_REPORT_TIPS = 206,
    /** 发送 */
    CHAT_SEND = 207,
    /** 系统 */
    CHAT_SYSTEM = 208,
    /** 系统公告 */
    CHAT_SYSTEM_TITLE = 209,
    /** 国家 */
    CHAT_TAB_GJ = 210,
    /** 黑名单 */
    CHAT_TAB_HMD = 211,
    /** 联盟 */
    CHAT_TAB_LM = 212,
    /** 世界 */
    CHAT_TAB_SJ = 213,
    /** 私聊 */
    CHAT_TAB_SL = 214,
    /** 聊天 */
    CHAT_TITLE = 215,
    /** 世界 */
    CHAT_WORLD = 216,
    /** 一键建造 */
    CITY_BD_ALL = 217,
    /** 贵族2开启一键建造 */
    CITY_BD_ALL_FAL = 218,
    /** 建造 */
    CITY_BD_BUILD = 219,
    /** 可招募兵种 */
    CITY_BD_BY_EF1 = 220,
    /** 兵力上限 */
    CITY_BD_BY_EF2 = 221,
    /** 攻击力 */
    CITY_BD_BY_EF3 = 222,
    /** 防御力 */
    CITY_BD_BY_EF4 = 223,
    /** 兵力 */
    CITY_BD_BY_EF5 = 224,
    /** 闲置 */
    CITY_BD_IDEL = 225,
    /** 正在建造中 */
    CITY_BD_IN = 226,
    /** <font color = #ff0000>%s 正在升级！</font> */
    CITY_BD_IN1 = 227,
    /** 获得银两加成 */
    CITY_BD_JBP_EF1 = 228,
    /** 获得元宝上限 */
    CITY_BD_JBP_EF2 = 229,
    /** 冷却时间 */
    CITY_BD_JBP_EF3 = 230,
    /** 每天产出上限 */
    CITY_BD_JG_CCSX = 231,
    /** 产出招募令(分钟) */
    CITY_BD_JG_EF = 232,
    /** 可解锁 */
    CITY_BD_KJS = 233,
    /** 武将等级上限提升至 */
    CITY_BD_LIMIT = 234,
    /** 所有建筑等级提升至<font color=#ffff99>%s</font>，可解锁以下建筑 */
    CITY_BD_LIMIT1 = 235,
    /** 建筑等级上限提升至 */
    CITY_BD_LIMIT2 = 236,
    /** 建筑未激活 */
    CITY_BD_LOCK = 237,
    /** 建筑未激活! */
    CITY_BD_LOCK1 = 238,
    /** 下一等级 */
    CITY_BD_LV_NEXT = 239,
    /** 该建筑已经达到当前最大等级 */
    CITY_BD_MAX = 240,
    /** 需要%s 等级：%s */
    CITY_BD_NEED = 241,
    /** <font color = #ff0000>需要%s 等级：%s</font> */
    CITY_BD_NEED_FAL = 242,
    /** <font color = #ff0000>需要%s个%s%s级     %s/%s</font> */
    CITY_BD_NEED_FAL1 = 243,
    /** 未找到建筑 */
    CITY_BD_NO = 244,
    /** 大殿%s级解锁 */
    CITY_BD_OPEN_DES = 245,
    /** 大殿%s级解锁！ */
    CITY_BD_OPEN_DES1 = 246,
    /** 建造队列已满 */
    CITY_BD_QUE_MAX = 247,
    /** 一键征收 */
    CITY_BD_REC_ALL = 248,
    /** 是否花费[img]icon_source_gold_png[/img]<font color = #e9e9e6> %s元宝</font>加速？ */
    CITY_BD_SPEED = 249,
    /** %s级 */
    CITY_BD_TITLE = 250,
    /** 建筑升级中 */
    CITY_BD_UP = 251,
    /** 画舫 */
    CITY_HF = 252,
    /** 资源储存上限 */
    CITY_INVENTORY = 253,
    /** 弩车 */
    CITY_NC = 254,
    /** 加速道具不足 */
    CITY_NOT_ITEM = 255,
    /** 水怪 */
    CITY_SG = 256,
    /** 你选择加速的时间大于计时器中的剩余时间%s分钟以上，确认使用？ */
    CITY_SP_TIME = 257,
    /** 投石车 */
    CITY_TSC = 258,
    /** 帐篷 */
    CITY_ZP = 259,
    /** 关闭 */
    CLOSE = 260,
    /** 合成 */
    COMPOSE = 261,
    /** 过关斩将积分不足 */
    CONQUER_LESS = 262,
    /** 聚宝盆 */
    CORN = 263,
    /** 今天聚宝次数已经达到上限 */
    CORN_GET_FAL = 264,
    /** 元宝不足%s,无法聚宝! */
    CORN_GET_FAL2 = 265,
    /** 聚宝 */
    CORN_JB = 266,
    /** 天 */
    DAY = 267,
    /** 防御 */
    DEFENSE = 268,
    /** 防御+%s */
    DEFENSE_ADD = 269,
    /** 效果 */
    EFFECT = 270,
    /** 进入游戏 */
    ENTER_GAME = 271,
    /** 锻造 */
    EQUIP = 272,
    /** 铠甲 */
    EQUIP_CLOTH = 273,
    /** 当前进阶阶段%s */
    EQUIP_CURR_JJJD = 274,
    /** 当前精炼阶段%s */
    EQUIP_CURR_JLJD = 275,
    /** 当前强化阶段%s */
    EQUIP_CURR_QHJD = 276,
    /** <font color = #00ff00>+%s</font> */
    EQUIP_DS_COLOR = 277,
    /** 你的装备已满，请立即前往回收或调整装备。 */
    EQUIP_FULL = 278,
    /** 进阶等级已达最高 */
    EQUIP_GRADE_FULL = 279,
    /** 合成 */
    EQUIP_HC = 280,
    /** 一键合成 */
    EQUIP_HC_ALL = 281,
    /** 没有可合成碎片 */
    EQUIP_HC_FAL = 282,
    /** 合成成功 */
    EQUIP_HC_SUC = 283,
    /** 头盔 */
    EQUIP_HEAD = 284,
    /** 进阶阶段%s */
    EQUIP_JJ_JIED = 285,
    /** 精炼阶段%s */
    EQUIP_JL_JIED = 286,
    /** 精炼%s级解锁 */
    EQUIP_JL_OPEN = 287,
    /** 提升武将等级增加可精炼上限 */
    EQUIP_JL_TIPS = 288,
    /** 武将等级达到<font color=#ffff99>%s</font>级后可进行精炼 */
    EQUIP_JL_TIPS1 = 289,
    /** 精炼大师 */
    EQUIP_JLJC = 290,
    /** 精炼进度 */
    EQUIP_JLJD = 291,
    /** 强化等级已达最高 */
    EQUIP_LEVEL_FULL = 292,
    /** 下一级进阶阶段%s */
    EQUIP_NEXT_JJJD = 293,
    /** 下一级精炼阶段%s */
    EQUIP_NEXT_JLJD = 294,
    /** 下一级强化阶段%s */
    EQUIP_NEXT_QHJD = 295,
    /** 全身精炼%s级开启 */
    EQUIP_OPEN_JL = 296,
    /** 全身强化%s级开启 */
    EQUIP_OPEN_QH = 297,
    /** 全身升阶为%s级开启 */
    EQUIP_OPEN_SJ = 298,
    /** 强化阶段%s */
    EQUIP_QH_JIED = 299,
    /** 提升武将等级增加可强化上限 */
    EQUIP_QH_TIPS = 300,
    /** 武将等级达到<font color=#ffff99>%s</font>级后可进行强化 */
    EQUIP_QH_TIPS1 = 301,
    /** 强化大师 */
    EQUIP_QHJC = 302,
    /** 强化进度 */
    EQUIP_QHJD = 303,
    /** (回收装备获得一定数量的强化石) */
    EQUIP_RECOVER_TIPS = 304,
    /** 鞋子 */
    EQUIP_SHOE = 305,
    /** 提升武将等级增加可升阶上限 */
    EQUIP_SJ_TIPS = 306,
    /** 武将等级达到<font color=#ffff99>%s</font>级后可进行升阶 */
    EQUIP_SJ_TIPS1 = 307,
    /** 升阶大师 */
    EQUIP_SJJC = 308,
    /** 升阶进度 */
    EQUIP_SJJD = 309,
    /** 你的碎片已满，请立即前往合成装备。 */
    EQUIP_SOUL_FULL = 310,
    /** 主属性：<font color=%s}>0</font> */
    EQUIP_SX_AD = 311,
    /** 主属性：<font color=%s>0（+%s%）</font> */
    EQUIP_SX_AD1 = 312,
    /** %s：<font color=%s}>0</font> */
    EQUIP_SX_AD2 = 313,
    /** %s：<font color=%s>%s（+%s%）</font> */
    EQUIP_SX_AD3 = 314,
    /** 碎片 */
    EQUIP_TAB_HC = 315,
    /** 回收 */
    EQUIP_TAB_HS = 316,
    /** 精炼 */
    EQUIP_TAB_JL = 317,
    /** 强化 */
    EQUIP_TAB_QH = 318,
    /** 升阶 */
    EQUIP_TAB_SJ = 319,
    /** 装备 */
    EQUIP_TAB_ZB = 320,
    /** 当前已激活 */
    EQUIP_TIPS_JH = 321,
    /** 装备穿戴 */
    EQUIP_TITLE_CD = 322,
    /** <font color=#ff0000>(穿戴后激活)</font> */
    EQUIP_TITLE_CDJH = 323,
    /** <font color=%s>2件套：</font> */
    EQUIP_TITLE_COLOR_TZ2 = 324,
    /** <font color=%s>3件套：</font> */
    EQUIP_TITLE_COLOR_TZ3 = 325,
    /** <font color=%s>4件套：</font> */
    EQUIP_TITLE_COLOR_TZ4 = 326,
    /** 精炼属性 */
    EQUIP_TITLE_JLSX = 327,
    /** 强化属性 */
    EQUIP_TITLE_QHSX = 328,
    /** 阶数 */
    EQUIP_TITLE_SJJS = 329,
    /** 升阶属性 */
    EQUIP_TITLE_SJSX = 330,
    /** 2件套： */
    EQUIP_TITLE_TZ2 = 331,
    /** 3件套： */
    EQUIP_TITLE_TZ3 = 332,
    /** 4件套： */
    EQUIP_TITLE_TZ4 = 333,
    /** <font color=#00ff00>(已激活)</font> */
    EQUIP_TITLE_YJH = 334,
    /** 属性总览 */
    EQUIP_TITLE_ZBSX = 335,
    /** 前往合成 */
    EQUIP_TO_COMPOSE = 336,
    /** 前往回收 */
    EQUIP_TO_RECOVER = 337,
    /** 武器 */
    EQUIP_WEAPON = 338,
    /** 精炼等级已达最高 */
    EQUIP_WROUGH_FULL = 339,
    /** 武将没有可穿戴装备 */
    EQUIP_ZB_FAL = 340,
    /** 更换 */
    EQUIP_ZB_GH = 341,
    /** 没有可回收装备 */
    EQUIP_ZB_SH_FAL = 342,
    /** 选择<font color = #e938f2>紫色</font>品质以上装备，回收将使物品永久消失，是否确定回收? */
    EQUIP_ZB_SH_TIPS = 343,
    /** 包含<font color = #e938f2>紫色</font>品质以上装备，回收将使物品永久消失，是否确定回收? */
    EQUIP_ZB_SH_TIPS1 = 344,
    /** 未穿戴 */
    EQUIP_ZB_WCD = 345,
    /** 卸下 */
    EQUIP_ZB_XX = 346,
    /** 已穿戴 */
    EQUIP_ZB_YCD = 347,
    /** 精炼5级 */
    EQUIP_ZB_YJJL = 348,
    /** 强化5级 */
    EQUIP_ZB_YJQH = 349,
    /** 升阶5级 */
    EQUIP_ZB_YJSJ = 350,
    /** 一键卸装 */
    EQUIP_ZB_YJXZ = 351,
    /** 一键装备 */
    EQUIP_ZB_YJZB = 352,
    /** 兑换成功 */
    EXCHANGE_SUC = 353,
    /** 战功 */
    EXPLOIT = 354,
    /** 第%s阶段 */
    EXPLOIT_AWARD_LV = 355,
    /** 战功不足 */
    EXPLOIT_BUY_FAL = 356,
    /** 1、大地图剿匪可以获得战功\n\n2、参加大地图攻城战可以获得战功\n\n */
    EXPLOIT_HELP_DESC = 357,
    /** 开启宝箱 */
    EXPLOIT_KQBX = 358,
    /** 战功不足 */
    EXPLOIT_LESS = 359,
    /** 国战奖励 */
    EXPLOIT_TAB_GZ = 360,
    /** 排名奖励 */
    EXPLOIT_TAB_PM = 361,
    /** 战功商城 */
    EXPLOIT_TAB_ZG = 362,
    /** 战功每周星期一凌晨<font color = #e9e9e6>0</font>点清零,请各位主公及时使用 */
    EXPLOIT_TIPS = 363,
    /** 获取战功 */
    EXPLOIT_TITLE = 364,
    /** 已经领取 */
    EXPLOIT_YJLQ = 365,
    /** 战斗力 */
    FIGHT = 366,
    /** 战斗力<font color=#00ff00>+%s</font> */
    FIGHT_ADD = 367,
    /** <font color = 0xff0000>战斗力:%s</font> */
    FIGHT_CUT = 368,
    /** 战斗力： */
    FIGHT1 = 369,
    /** 完成 */
    FINISH = 370,
    /** 立即完成 */
    FINISH_SOON = 371,
    /** 粮食 */
    FOOD = 372,
    /** 粮食不足 */
    FOOD_LESS = 373,
    /** %s级提升 */
    FUNC_LEVEL = 374,
    /** 功能未开放！ */
    FUNC_LOCK = 375,
    /** 激活建筑【%s】解锁！ */
    FUNC_OPEN_BUILD = 376,
    /** 君主等级到达%s级开启！ */
    FUNC_OPEN_LEVEL = 377,
    /** %s级开启 */
    FUNC_OPEN_LIMIT = 378,
    /** 【%s】开启！ */
    FUNC_OPEN_TASK = 379,
    /** 未开启 */
    FUNC_UNOPEN = 380,
    /** 刀兵属性 */
    GEN_ATT_DB = 381,
    /** 弓兵属性 */
    GEN_ATT_GB = 382,
    /** 基础属性 */
    GEN_ATT_JCSX = 383,
    /** 骑兵属性 */
    GEN_ATT_QB = 384,
    /** 枪兵属性 */
    GEN_ATT_QBI = 385,
    /** 统帅 */
    GEN_ATT_TY = 386,
    /** 大幅提升武将血量，小幅提升武将防御 */
    GEN_ATT_TY_TIPS = 387,
    /** 武力 */
    GEN_ATT_WL = 388,
    /** 大幅提升武将攻击，小幅提升武将血量 */
    GEN_ATT_WL_TIPS = 389,
    /** 智力 */
    GEN_ATT_ZL = 390,
    /** 大幅提升武将防御，小幅提升武将攻击 */
    GEN_ATT_ZL_TIPS = 391,
    /** 主属性 */
    GEN_ATT_ZSX = 392,
    /** 属性 */
    GEN_ATTR = 393,
    /** 经验 +%s */
    GEN_EXP_AD = 394,
    /** 额外获得%sx%s */
    GEN_GET_EWHD = 395,
    /** 合成 */
    GEN_GET_HC = 396,
    /** 获得途径 */
    GEN_GET_HDTJ = 397,
    /** 拥有数量:%s */
    GEN_GET_YYSL = 398,
    /** <font color=#aac7ff>武将等级提升至</font><font color=#ffff99>%s</font> */
    GEN_LEVEL = 399,
    /** 经验书不足，无法升级 */
    GEN_LEVEL_FAL = 400,
    /** 一键升级 */
    GEN_LEVEL_UP = 401,
    /** 级 */
    GEN_LEVEL1 = 402,
    /** 君主等级不足%s级，武将最高提升到%s级 */
    GEN_LV_LIMIT = 403,
    /** 武将等级已达上限，请先突破 */
    GEN_LV_LIMIT1 = 404,
    /** 君主等级达到 */
    GEN_ROLE_LEVEL = 405,
    /** 技能 */
    GEN_SKILL = 406,
    /** %s不足，无法升级 */
    GEN_SKILL_FAL = 407,
    /** 被动技能不可升级 */
    GEN_SKILL_FAL1 = 408,
    /** 该技能不可升级 */
    GEN_SKILL_FAL2 = 409,
    /** 技能升级需要武将等级达到%s级 */
    GEN_SKILL_LIMIT = 410,
    /** 技能升级需要武将星级达到%s级 */
    GEN_SKILL_LIMIT1 = 411,
    /** %s级\n%s星开启 */
    GEN_SKILL_OP_DES = 412,
    /** 武将%s级且总共%s星开启 */
    GEN_SKILL_OP_DES1 = 413,
    /** %s级开启 */
    GEN_SKILL_OP_DES2 = 414,
    /** %s星开启 */
    GEN_SKILL_OP_DES3 = 415,
    /** %s不足，无法升星 */
    GEN_STAR_FAL = 416,
    /** 升级 */
    GEN_STRENG = 417,
    /** 全部 */
    GEN_TAB_ALL = 418,
    /** 刀将 */
    GEN_TAB_BB = 419,
    /** 弓将 */
    GEN_TAB_GB = 420,
    /** 骑将 */
    GEN_TAB_QB = 421,
    /** 枪将 */
    GEN_TAB_QB1 = 422,
    /** 宝物装备 */
    GEN_TITLE_BWZB = 423,
    /** 技能升级 */
    GEN_TITLE_SKILL = 424,
    /** 武将列表 */
    GEN_TITLE_WJLB = 425,
    /** 武将详细 */
    GEN_TITLE_WJXX = 426,
    /** 宝物 */
    GEN_TREA = 427,
    /** 宝石套装%s/4 */
    GEN_TREA_BSTZ = 428,
    /** 没有可装备的宝物！ */
    GEN_TREA_NO = 429,
    /** 没有可替换的宝物! */
    GEN_TREA_NO1 = 430,
    /** 没有符合当前武将职业的宝物! */
    GEN_TREA_NO2 = 431,
    /** 装备 */
    GEN_TREA_ZB = 432,
    /** 突破 */
    GEN_TUPO = 433,
    /** 突破需要君主等级达到%s级 */
    GEN_TUPO_LEVEL = 434,
    /** 突破丹不足 */
    GEN_TUPO_NOENOUGH = 435,
    /** 去获得 */
    GO_GET = 436,
    /** 去升级 */
    GO_LEVEL = 437,
    /** 去加速 */
    GO_SPEED = 438,
    /** 去研发 */
    GO_TECHNO = 439,
    /** 前往 */
    GO_TO = 440,
    /** 前往中 */
    GO_TO1 = 441,
    /** 元宝 */
    GOLD = 442,
    /** 元宝不足 */
    GOLD_LESS = 443,
    /** 元宝不足，是否前往充值界面购买 */
    GOLD_LESS_TIPS = 444,
    /** 阶级 */
    GRADE = 445,
    /** 升阶 */
    GRADE_UP = 446,
    /** 已满阶 */
    GRADE_UP_MAX = 447,
    /** 满阶 */
    GRADE_UP_MAX1 = 448,
    /** 阶数 */
    GRADE1 = 449,
    /** %s阶 */
    GRADE2 = 450,
    /** 最多可输入100个字符 */
    GUI_NOTICE_LIMIT = 451,
    /** 联盟贡献 */
    GUI_POINT = 452,
    /** 联盟个人贡献不足 */
    GUI_POINT_LESS = 453,
    /** 未发现此联盟 */
    GUI_SEARCH_FAL = 454,
    /** 搜索内容不能为空 */
    GUI_SEARCH_FAL1 = 455,
    /** 联盟 */
    GUILD = 456,
    /** 申请 */
    GUILD_APPLY = 457,
    /** 需要大殿等级%s */
    GUILD_APPLY_FAL = 458,
    /** 请先选择联盟 */
    GUILD_APPLY_FAL1 = 459,
    /** 你已申请，请耐心等待验证 */
    GUILD_APPLY_IN = 460,
    /** 申请列表 */
    GUILD_APPLY_LIST = 461,
    /** 任命成功 */
    GUILD_APPLY_TIPS = 462,
    /** 贡献 */
    GUILD_CONTRIBUTE = 463,
    /** 创建联盟 */
    GUILD_CREATE = 464,
    /** 联盟已解散 */
    GUILD_DISS_TIPS = 465,
    /** 捐献 */
    GUILD_DONATE = 466,
    /** 今日次数已尽 */
    GUILD_DONATE_NONE = 467,
    /** 您已经加入工会！ */
    GUILD_ENTER_ALR = 468,
    /** 联盟战力 */
    GUILD_FIGHT = 469,
    /** 输入不符合 */
    GUILD_INPUT_FAL = 470,
    /** 联盟命名不能为空 */
    GUILD_INPUT_FAL1 = 471,
    /** 输入只能是数字 */
    GUILD_JION_LIMIT = 472,
    /** 加入设置 */
    GUILD_JION_SET = 473,
    /** 是否加入【%s】联盟? */
    GUILD_JION_YN = 474,
    /** 你被踢出联盟了 */
    GUILD_KICK_TIPS = 475,
    /** 离线 */
    GUILD_LINE_OFF = 476,
    /** 在线 */
    GUILD_LINE_ON = 477,
    /** 在线状态 */
    GUILD_LINE_STATE = 478,
    /** 成员名称 */
    GUILD_MEMBER_NAME = 479,
    /** 联盟消息 */
    GUILD_MSG = 480,
    /** %s 玩家%s<font color = #00F700>申请</font>%s【盟主】 */
    GUILD_MSG_APPLY = 481,
    /** %s 玩家%s<font color = #00F700>更改</font>%s联盟 */
    GUILD_MSG_CHANGE = 482,
    /** %s 联盟%s<font color = #00F700>创建</font>成功 */
    GUILD_MSG_CREATE = 483,
    /** %s 玩家%s<font color = #00F700>加入</font>成功 */
    GUILD_MSG_JION = 484,
    /** %s 玩家%s被【%s】%s <font color = #00F700>踢出</font>联盟 */
    GUILD_MSG_KICK = 485,
    /** %s 玩家%s<font color = #00F700>退出</font>联盟 */
    GUILD_MSG_LEAVE = 486,
    /** %s 玩家%s<font color = #00F700>成为</font>新的【%s】 */
    GUILD_MSG_NEW = 487,
    /** %s 玩家%s被<font color = #00F700>任命</font>为【%s】 */
    GUILD_MSG_RM = 488,
    /** 联盟名字 */
    GUILD_NAME = 489,
    /** 联盟宣言 */
    GUILD_NOTICE = 490,
    /** 人数 */
    GUILD_NUM = 491,
    /** 操作 */
    GUILD_OPERA = 492,
    /** 查看玩家 */
    GUILD_OPERA_CKWJ = 493,
    /** 任命 */
    GUILD_OPERA_RM = 494,
    /** 退出 */
    GUILD_OPERA_TC = 495,
    /** 踢出 */
    GUILD_OPERA_TCWJ = 496,
    /** 转让 */
    GUILD_OPERA_ZR = 497,
    /** 职位 */
    GUILD_POS = 498,
    /** 成员 */
    GUILD_POS_CY = 499,
    /** 成员： */
    GUILD_POS_CY1 = 500,
    /** 副盟主 */
    GUILD_POS_FMZ = 501,
    /** 核心 */
    GUILD_POS_HX = 502,
    /** 精英 */
    GUILD_POS_JY = 503,
    /** 盟主 */
    GUILD_POS_MZ = 504,
    /** 盟主： */
    GUILD_POS_MZ1 = 505,
    /** 设置成功 */
    GUILD_SET_TIPS = 506,
    /** 设置 */
    GUILD_SHEZHI = 507,
    /** 贡献排名 */
    GUILD_TAB_GX = 508,
    /** 商店 */
    GUILD_TAB_SHOP = 509,
    /** 进盟时间 */
    GUILD_TAB_SJ = 510,
    /** 科技 */
    GUILD_TAB_TECHNO = 511,
    /** 战力排名 */
    GUILD_TAB_ZL = 512,
    /** 今日在线 */
    GUILD_TAB_ZX = 513,
    /** 科技等级已达最高 */
    GUILD_TECH_MAX = 514,
    /** 您确定要解散联盟？ */
    GUILD_TIPS_JSLM = 515,
    /** 让位成功 */
    GUILD_TIPS_RWCG = 516,
    /** 剔除成功! */
    GUILD_TIPS_TCCG = 517,
    /** 你已退出联盟 */
    GUILD_TIPS_TCLM = 518,
    /** 盟主只有转换身份才能退出联盟 */
    GUILD_TIPS_TCLM_FAL = 519,
    /** 是否退出联盟？ */
    GUILD_TIPS_TCLM1 = 520,
    /** 是否确定踢出该玩家？ */
    GUILD_TIPS_TCWJ = 521,
    /** 确认转让盟主？ */
    GUILD_TIPS_ZRMZ = 522,
    /** 联盟科技 */
    GUILD_TITEL_TECH = 523,
    /** 自动挑战 */
    HAN_AUTO = 524,
    /** 已经开启自动挑战 */
    HAN_AUTO_ALR = 525,
    /** 离线收益 */
    HAN_AWARD_OFF = 526,
    /** 距离上次领奖不足%s秒，请稍后！ */
    HAN_AWARD_TIPS = 527,
    /** 购买次数 */
    HAN_BOS_BUY = 528,
    /** 是否花费[img]icon_source_gold_png[/img]<font color = #e9e9e6>%s元宝</font>购买挑战次数？ */
    HAN_BOS_BUY_TIME = 529,
    /** 在线挂机可以召唤入侵<font color = #ff0000>BOSS</font>，击杀后有几率可获得大量奖励！ */
    HAN_BOS_DES = 530,
    /** 击杀%s敌人可召唤<font color = #ff0000>BOSS</font> */
    HAN_BOS_POR = 531,
    /** 敌将入侵 */
    HAN_BOS_TILE = 532,
    /** （今日奖励次数<font color = #e9e9e6>%s/%s</font>） */
    HAN_BOS_TIPS = 533,
    /** 需要等级%s */
    HAN_FIGHT_LIMIT = 534,
    /** 需要再挂机击退%s敌人 */
    HAN_FIGHT_TIPS = 535,
    /** 点击挑战！ */
    HAN_FIGHT_TIPS1 = 536,
    /** 领取武将! */
    HAN_GET_GEN = 537,
    /** 击杀了%s个敌人 */
    HAN_KILL_TIPS = 538,
    /** 通关%s关送%s */
    HAN_PASS_TIPS = 539,
    /** <font color=#E7D7A7>立即获得</font><font color=#00ff00>%s小时</font><font color=#E7D7A7>加速</font> */
    HAN_SPEED_TIPS = 540,
    /** 提升贵族等级可以增加次数 */
    HAN_SPEED_TIPS1 = 541,
    /** 今日不能再购买次数 */
    HAN_SPEED_TIPS2 = 542,
    /** <font color=#E7D7A7>离线时长：</font><font color=#00ff00>%s</font><font color=#00ff00>小时</font><font color=#00ff00>%s</font><font color=#00ff00>分钟</font> */
    HAN_TIPS = 543,
    /** <font color=#4D3322>离线收益最多：</font><font color=#4D3322>%s</font><font color=#4D3322>小时</font> */
    HAN_TIPS1 = 544,
    /** <font color=#4D3322>(在游戏左下角宝箱中领取奖励,提升</font><font color=#ff0000>贵族</font><font color=#4D3322>等级可延长收益时间)</font> */
    HAN_TIPS2 = 545,
    /** 恭喜通关:%s */
    HAN_TIPS3 = 546,
    /** 收益变化 */
    HAN_TITLE_CHAN = 547,
    /** 收益加速 */
    HAN_TITLE_SPEED = 548,
    /** 战利品 */
    HAN_WAR_AWARD = 549,
    /** 困难 */
    HARD = 550,
    /** 小时 */
    HOUR = 551,
    /** %s/小时 */
    HOUR1 = 552,
    /** 血量+%s */
    HP_ADD = 553,
    /** 铁 */
    IRON = 554,
    /** 铁矿不足 */
    IRON_LESS = 555,
    /** 联盟： */
    LEGION = 556,
    /** 级 */
    LEVEL = 557,
    /** 等级<font color=#00ff00>+%s</font> */
    LEVEL_ADD = 558,
    /** 等级不足 */
    LEVEL_LESS = 559,
    /** 已达最大等级 */
    LEVEL_MAX = 560,
    /** 已满级 */
    LEVEL_MAX1 = 561,
    /** 满级 */
    LEVEL_MAX2 = 562,
    /** %s等级：%s */
    LEVEL_NEED = 563,
    /** <font color = #ff0000>需要%s等级：%s</font> */
    LEVEL_NEED_FAL = 564,
    /** 升级 */
    LEVEL_UP = 565,
    /** 升级5级 */
    LEVEL_UP1 = 566,
    /** %s级 */
    LEVEL1 = 567,
    /** 等级 */
    LEVEL2 = 568,
    /** 等级： */
    LEVEL3 = 569,
    /** 更换形象 */
    LOGIN_CH_IMG = 570,
    /** 更换名字 */
    LOGIN_CH_NAME = 571,
    /** 请先选择角色名 */
    LOGIN_CHOSE_NAME = 572,
    /** 请先选择国家 */
    LOGIN_CHOSE_STATE = 573,
    /** 更换形象成功 */
    LOGIN_CIMG = 574,
    /** 名称更换成功 */
    LOGIN_CNAME = 575,
    /** 请输入3到6个字符 */
    LOGIN_LIMIT = 576,
    /** 名字不能为空 */
    LOGIN_NOT_NU = 577,
    /** 邮件 */
    MAIL = 578,
    /** 领取附件 */
    MAIL_ATT_GET = 579,
    /** 领取附件失败 */
    MAIL_ATT_GET_FAL = 580,
    /** 删除 */
    MAIL_DEL = 581,
    /** 一键删除 */
    MAIL_DEL_ALL = 582,
    /** 邮件删除失败 */
    MAIL_DEL_FAL = 583,
    /** 没有邮件 */
    MAIL_NONE = 584,
    /** 一键阅读 */
    MAIL_READ_ALL = 585,
    /** 没有可读邮件 */
    MAIL_READ_NONE = 586,
    /** 当前没有选中的邮件 */
    MAIL_SEL_NONE = 587,
    /** 采集 */
    MAIL_TAB_CJ = 588,
    /** 个人 */
    MAIL_TAB_GR = 589,
    /** 国战 */
    MAIL_TAB_GZ = 590,
    /** 系统 */
    MAIL_TAB_ST = 591,
    /** 剿匪 */
    MAIL_TAB_ZF = 592,
    /** 是否删除所有%s邮件? */
    MAIL_TIPS_DEL = 593,
    /** 第%s战 */
    MAIL_TITLE_FIGHT = 594,
    /** 物资征战 */
    MAT = 595,
    /** 购买成功 */
    MAT_BUY_SUC = 596,
    /** 挑战次数已满 */
    MAT_FIGHT_MAX = 597,
    /** 挑战次数不足 */
    MAT_NO_NUMBER = 598,
    /** 扫荡 */
    MAT_SWEEP_FREE = 599,
    /** 部队副本 */
    MAT_TAB_BD = 600,
    /** 精炼副本 */
    MAT_TAB_JL = 601,
    /** 强化副本 */
    MAT_TAB_QH = 602,
    /** 升阶副本 */
    MAT_TAB_SJ = 603,
    /** 银两副本 */
    MAT_TAB_YL = 604,
    /** 当前已无可进行购买的挑战次数，提高贵族等级可增加 */
    MAT_TIPS_GMCS = 605,
    /** 每日凌晨<font color=#e9e9e6>6</font>点重置 */
    MAT_TIPS_RESET = 606,
    /** 通关%s开启 */
    MAT_TIPS_TGKQ = 607,
    /** 信息 */
    MESSAGE = 608,
    /** 分钟 */
    MIN = 609,
    /** 君主 */
    MONACH = 610,
    /** 暂无描述 */
    NO_DES = 611,
    /** 无 */
    NONE = 612,
    /** 普通 */
    NORMAL = 613,
    /** 公  告 */
    NOTICE_TITLE = 614,
    /** 百 */
    NUM_BAI = 615,
    /** 千 */
    NUM_QIAN = 616,
    /** 十 */
    NUM_SHI = 617,
    /** 万 */
    NUM_WAN = 618,
    /** 亿 */
    NUM_YI = 619,
    /** 零 */
    NUM0 = 620,
    /** 一 */
    NUM1 = 621,
    /** 二 */
    NUM2 = 622,
    /** 三 */
    NUM3 = 623,
    /** 四 */
    NUM4 = 624,
    /** 五 */
    NUM5 = 625,
    /** 六 */
    NUM6 = 626,
    /** 七 */
    NUM7 = 627,
    /** 八 */
    NUM8 = 628,
    /** 九 */
    NUM9 = 629,
    /** %s个 */
    PIECE = 630,
    /** 玩家信息 */
    PLATER_INFO = 631,
    /** 职位： */
    POST = 632,
    /** 竞技勋章 */
    PVP_MEDAL = 633,
    /** 竞技勋章不足 */
    PVP_MEDAL_LESS = 634,
    /** 开启宝箱需要本章节星级达到%s星! */
    QUA_BOX_LIMIT = 635,
    /** 宝箱已领取！ */
    QUA_BOX_TIPS = 636,
    /** 掉落 */
    QUA_FALL = 637,
    /** 首次掉落 */
    QUA_FALL_FIRST = 638,
    /** 今日购买次数已用完，是否前往充值界面提升贵族等级？ */
    QUA_FI_BUY_MAX = 639,
    /** 您的挑战次数不足，自动花费\n[img]icon_source_gold_png[/img]<font color = #E9E9E6>{1}元宝</font>购买<font color = #E9E9E6>1</font>次？ */
    QUA_FI_COST_DES = 640,
    /** 通关%s解锁 */
    QUA_PASS_LIMIT = 641,
    /** %s后恢复1次次数 */
    QUA_RESUME_TIPS = 642,
    /** 此卡已达最大扫荡上限 */
    QUA_SWEEP_FAL = 643,
    /** 排行榜 */
    RANK = 644,
    /** 城池排行 */
    RANK_CITY = 645,
    /** 等级排名 */
    RANK_LEVEL = 646,
    /** 联盟排行 */
    RANK_LM = 647,
    /** 未上榜 */
    RANK_NONE = 648,
    /** 第%s名 */
    RANK_NUM = 649,
    /** 战力排名 */
    RANK_POWER = 650,
    /** 武将排行 */
    RANK_WJ = 651,
    /** 战功排行 */
    RANK_ZG = 652,
    /** 战力排行 */
    RANK_ZL = 653,
    /** 回收 */
    RECOVER = 654,
    /** 批量回收 */
    RECOVER_MUL = 655,
    /** 退出(9) */
    RESULT_EXIT = 656,
    /** 确定(%s) */
    RESULT_SURE = 657,
    /** 拒绝 */
    RESURE = 658,
    /** 礼包兑换 */
    ROLE_GIFT_DH = 659,
    /** 个人信息 */
    ROLE_INFO = 660,
    /** 立即兑换 */
    ROLE_LJ_DH = 661,
    /** 更换形象 */
    ROLE_LOOK_CHANGE = 662,
    /** 请输入礼包兑换码 */
    ROLE_SHURU_DH = 663,
    /** 秒 */
    SEC = 664,
    /** 商城 */
    SHOP = 665,
    /** <font color>限购  %s/%s */
    SHOP_BUY_LIMIT = 666,
    /** 已达购买上限 */
    SHOP_BUY_MAX = 667,
    /** 购买成功 */
    SHOP_BUY_SUC = 668,
    /** %s折 */
    SHOP_DISCOUNT = 669,
    /** 免单商城 */
    SHOP_FREE = 670,
    /** %s购买<font color=%s>%s</font>获得免单 */
    SHOP_FREE_MSG = 671,
    /** 免单记录 */
    SHOP_FREE_REC = 672,
    /** 已售罄 */
    SHOP_ITEM_EMPTY = 673,
    /** <font color = #ABB7D1>今日限购  </font>%s/%s */
    SHOP_LIMIT = 674,
    /** 限购%s/%s次 */
    SHOP_LIMIT1 = 675,
    /** 下次刷新时间： */
    SHOP_NEXT_TIME = 676,
    /** 库存： */
    SHOP_NUM_LEFT = 677,
    /** <font color = #ABB7D1>下次刷新时间：</font>%s */
    SHOP_RUSH_DES = 678,
    /** 免费刷新 */
    SHOP_RUSH_FREE = 679,
    /** <font color = #ABB7D1>免费刷新次数:</font>%s */
    SHOP_RUSH_FREE1 = 680,
    /** 剩余刷新次数： */
    SHOP_RUSH_LEFT = 681,
    /** <font color = #ABB7D1>剩余刷新次数：</font>%s */
    SHOP_RUSH_LEFT1 = 682,
    /** 立即刷新 */
    SHOP_RUSH_NOW = 683,
    /** <font color = #ABB7D1>每天<font color = #E9E9E6>%s</font>点重置</font> */
    SHOP_RUSH_RESET = 684,
    /** 宝石商城 */
    SHOP_TAB_BS = 685,
    /** 贵族商城 */
    SHOP_TAB_GZ = 686,
    /** 竞技商城 */
    SHOP_TAB_JJ = 687,
    /** 技能商城 */
    SHOP_TAB_JN = 688,
    /** 联盟商城 */
    SHOP_TAB_LM = 689,
    /** 武将商城 */
    SHOP_TAB_WJ = 690,
    /** 珍宝商城 */
    SHOP_TAB_ZB = 691,
    /** 斩将商城 */
    SHOP_TAB_ZJ = 692,
    /** 贵族%s解锁 */
    SHOP_VIP_LIMIT = 693,
    /** 银两 */
    SILVER = 694,
    /** 银两不足 */
    SILVER_LESS = 695,
    /** 来源 */
    SOURCE = 696,
    /** 获取途径 */
    SOURCE_PATH = 697,
    /** 加速 */
    SPEED_AD = 698,
    /** 星 */
    STAR = 699,
    /** 星级<font color=#00ff00>+%s</font> */
    STAR_ADD = 700,
    /** 已达最大星级 */
    STAR_MAX = 701,
    /** 已满星 */
    STAR_MAX1 = 702,
    /** 满星 */
    STAR_MAX2 = 703,
    /** 升星 */
    STAR_UP = 704,
    /** %s星 */
    STAR1 = 705,
    /** 星级 */
    STAR2 = 706,
    /** 国家 */
    STATE = 707,
    /** 1、国家有多个官职，并有对应的俸禄和特权\n\n2、官职俸禄每日21点发放，特权则在获得官职后立刻生效\n\n3、玩家的国战战功累计达到一定数额后即可获得官职，战功高者先得\n\n4、攻克王城的战功最高玩家获得王位\n\n5、君王三天不上线可被官员弹劾，弹劾支持者数达到要求后，弹劾成功则弹劾发起者成为君王 */
    STATE_BZWD = 708,
    /** 是否卸除您当前城池？ */
    STATE_CITY_XR_TIPS = 709,
    /** 弹劾 */
    STATE_DH = 710,
    /** 国家官职 */
    STATE_GZ = 711,
    /** 空缺 */
    STATE_GZ_EMPTY = 712,
    /** 更换 */
    STATE_GZ_GH = 713,
    /** 任命 */
    STATE_GZ_RM = 714,
    /** 禅让 */
    STATE_GZ_SR = 715,
    /** 禅让成功 */
    STATE_GZ_SR_TIPS = 716,
    /** <font color=#ffff99>%s</font>正在发起弹劾（支持者%d/%d） */
    STATE_GZ_TAN_HE = 717,
    /** 剩余时间：<font color=#00ff00>%s</font> */
    STATE_GZ_TIME = 718,
    /** 卸任 */
    STATE_GZ_XR = 719,
    /** 是否卸任自身官职 */
    STATE_GZ_XR_TIPS = 720,
    /** 卸任成功 */
    STATE_GZ_XR_TIPS1 = 721,
    /** 虚位以待 */
    STATE_GZ_XWYD = 722,
    /** %s战功 */
    STATE_GZ_ZG = 723,
    /** 黄巾 */
    STATE_HUANGJIN = 724,
    /** 黄 */
    STATE_HUANG = 725,
    /** 恭喜<font color=#e7c772>%s</font>成为%s国国王 */
    STATE_KING_TIPS = 726,
    /** 烽火岁月，乱世英雄，聚天下之英杰，称雄十三州。\n欢迎各位主公的到来，在这里不论身份贵贱，不论财富势权，皆为一国手足。征战路途之遥远，望诸位风雨同舟，有难互助，共创宏图霸业。 */
    STATE_NOTICE = 727,
    /** 群 */
    STATE_QUN = 728,
    /** 是否任命%s为%s？\n此操作将会把现担任官职的玩家卸除！ */
    STATE_RM_TIPS = 729,
    /** 是否禅让君王给%s？ */
    STATE_RW_TIPS = 730,
    /** 蜀 */
    STATE_SHU = 731,
    /** 蜀国 */
    STATE_SHU_NA = 732,
    /** 国家任务 */
    STATE_TAB_DS = 733,
    /** 城镇管理 */
    STATE_TAB_GL = 734,
    /** 国家官职 */
    STATE_TAB_GZ = 735,
    /** 国家信息 */
    STATE_TAB_INFO = 736,
    /** 国战情报 */
    STATE_TAB_GZQB = 737,
    /** 国家公告 */
    STATE_TITLE_NOT = 738,
    /** 魏 */
    STATE_WEI = 739,
    /** 魏国 */
    STATE_WEI_NA = 740,
    /** 吴 */
    STATE_WU = 741,
    /** 吴国 */
    STATE_WU_NA = 742,
    /** 野 */
    STATE_YE = 743,
    /** 中立 */
    STATE_ZL = 744,
    /** 强化 */
    STRENG = 745,
    /** 确定 */
    SURE = 746,
    /** 领取 */
    TAKE_OUT = 747,
    /** 已领取 */
    TAKE_OUT_END = 748,
    /** 可领取 */
    TAKE_OUT_IN = 749,
    /** 任务 */
    TASK = 750,
    /** <font color = 0xE9E9E6>我的活跃度: </font>%s */
    TASK_ACTIVITY_NUM = 751,
    /** 活跃度 +%s */
    TASK_ACTIVITY_NUM1 = 752,
    /** 一键领取 */
    TASK_GET_ALL = 753,
    /** 培养任务 */
    TASK_TAB_PY = 754,
    /** 日常任务 */
    TASK_TAB_RC = 755,
    /** 主城任务 */
    TASK_TAB_ZC = 756,
    /** 主线任务 */
    TASK_TAB_ZX = 757,
    /** <font size = 20 color = #FFFFFF>%s</font>\n<font size = 18 color = #44d0f3>领取奖励</font> */
    TASK_TIPS = 758,
    /** 招募 */
    TAVEN = 759,
    /** 英雄预览 */
    TAVEN_HREO = 760,
    /** <font color=#FFFFFF>招募</font><font color=#F3A549>%s</font><font color=#FFFFFF>次必出</font><font color=#F3A549>整将</font> */
    TAVEN_TIPS_EW = 761,
    /** 科技 */
    TEC = 762,
    /** 前置科技等级不足 */
    TEC_BE_LESS = 763,
    /** 未知科技名字 */
    TEC_DEF_NAME = 764,
    /** 发展 */
    TEC_FZ = 765,
    /** 辅助 */
    TEC_FZKJ = 766,
    /** 已达到最高级 */
    TEC_LEVEL_MAX = 767,
    /** 等级%s<font color=0xffd375>/%s</font> */
    TEC_LEVEL_NUM = 768,
    /** 已最大 */
    TEC_MAX_DES = 769,
    /** 科技名字 */
    TEC_NAME = 770,
    /** 科技升级中 */
    TEC_UP = 771,
    /** 科技研究同时只能进行一项，请等待研究结束或加速完成后再试 */
    TEC_UP_FAL = 772,
    /** 立即研究 */
    TEC_UP_NOW = 773,
    /** 研究 */
    TEC_UP_START = 774,
    /** %s天%s时%s分 */
    TIME = 775,
    /** %s天%s时 */
    TIME1 = 776,
    /** %s时%s分 */
    TIME2 = 777,
    /** %s分%s秒 */
    TIME3 = 778,
    /** 提 示 */
    TIPS = 779,
    /** 宝物 */
    TREA = 780,
    /** 选择宝石 */
    TREA_BS_CHOSE = 781,
    /** 合成成功！ */
    TREA_BS_HCCG = 782,
    /** 宝物星级达到【%s级】开放! */
    TREA_BS_OPEN = 783,
    /** 同类型宝石只能镶嵌一个！ */
    TREA_BS_TIPS = 784,
    /** 没有可镶嵌宝石！ */
    TREA_BS_TIPS1 = 785,
    /** 宝石套装%s/4 */
    TREA_BS_TZ = 786,
    /** 镶嵌 */
    TREA_BS_XQ = 787,
    /** 请选择升级宝石！ */
    TREA_BSHC_FAL = 788,
    /** 所需宝石数量不足！ */
    TREA_BSHC_FAL1 = 789,
    /** 当前宝石已经是最高级！ */
    TREA_BSHC_TIPS = 790,
    /** 升级下一级宝石需要藏宝阁等级达到%s级！ */
    TREA_BSHC_TIPS1 = 791,
    /** 宝物未激活！ */
    TREA_BWWJH = 792,
    /** 升级属性 */
    TREA_LEVEL_ATTR = 793,
    /** 宝物已经达到最高等级！ */
    TREA_LEVEL_MAX = 794,
    /** 最大等级  */
    TREA_LV_MAX = 795,
    /** 升星属性 */
    TREA_STAR_ATTR = 796,
    /** 当前星级最高升级到%s级,提高星级可提高等级上限! */
    TREA_STAR_FAL = 797,
    /** 宝物已经达到最高星级！ */
    TREA_STAR_MAX = 798,
    /** 合成 */
    TREA_STOEN_HC = 799,
    /** 宝石孔  */
    TREA_STONE_BSK = 800,
    /** 孔%s */
    TREA_STONE_BSK2 = 801,
    /** %s星解锁 */
    TREA_STONE_JS = 802,
    /** 批量合成 */
    TREA_STONE_PL = 803,
    /** 未镶嵌 */
    TREA_STONE_WXQ = 804,
    /** 卸下 */
    TREA_STONE_XX = 805,
    /** 培养 */
    TREA_STRENG = 806,
    /** 全部 */
    TREA_TAB_ALL = 807,
    /** 兵器 */
    TREA_TAB_BQ = 808,
    /** 铠甲 */
    TREA_TAB_KJ = 809,
    /** 坐骑 */
    TREA_TAB_MP = 810,
    /** 奇物 */
    TREA_TAB_QW = 811,
    /** 书籍 */
    TREA_TAB_SJ = 812,
    /** 珍宝 */
    TREA_TAB_ZB = 813,
    /** 宝石 */
    TREA_TAG_HC = 814,
    /** 强化 */
    TREA_TAG_QH = 815,
    /** 属性 */
    TREA_TAG_SX = 816,
    /** 升星 */
    TREA_TAG_SXI = 817,
    /** 镶嵌 */
    TREA_TAG_XQ = 818,
    /** 宝物列表 */
    TREA_TITLE = 819,
    /** 卸下 */
    TREA_UNEQUIP = 820,
    /** 宝物升级成功，等级+%s */
    TREA_UP_TIPS = 821,
    /** 宝物升级失败，保留当前等级 */
    TREA_UP_TIPS1 = 822,
    /** 宝物升级失败，等级%s */
    TREA_UP_TIPS2 = 823,
    /** 使用道具 */
    USE_ITEM = 824,
    /** 贵族特权 */
    VIP = 825,
    /** 贵族%s可购买 */
    VIP_BUY_LIMIT = 826,
    /** 立即充值 */
    VIP_CHARGE_NOW = 827,
    /** 首次购买额外赠送 */
    VIP_FIRST_PAY_TIP = 828,
    /** 今日奖励已经领取 */
    VIP_GET_TIPS = 829,
    /** 贵族%s */
    VIP_LEVEL = 830,
    /** （当前贵族可购买次数<font color=#e9e9e6>%s</font>） */
    VIP_MAX_BUY = 831,
    /** 再充值<font color=#ffff99>%s元宝</font> 即可升级到<font color=#ffff99>贵族%s</font> */
    VIP_NEXT_TIPS = 832,
    /** 再充值<font color=#ffff99>%s元</font> 即可升级到<font color=#ffff99>贵族%s</font> */
    VIP_NEXT_TIPS1 = 833,
    /** 本次购买获得 */
    VIP_PAY_TIP = 834,
    /** 贵族特权 */
    VIP_PRIVIGE = 835,
    /** 贵族%s礼包 */
    VIP_PRIVIGE_GIFT = 836,
    /** 贵族%s特权 */
    VIP_PRIVIGE_LV = 837,
    /** 怒气不足 */
    WAR_ANGRT_FAL = 838,
    /** 攻击NPC出生点 */
    WAR_ATK_BORN = 839,
    /** 攻方 */
    WAR_ATTACK = 840,
    /** 箭塔 */
    WAR_BARTIZAN = 841,
    /** 防御NPC出生点 */
    WAR_DEF_BORN = 842,
    /** 守方 */
    WAR_DEFENSE = 843,
    /** 武将 */
    WAR_GEN = 844,
    /** 英雄已经死了 */
    WAR_HERO_DEAD = 845,
    /** 自动中 */
    WAR_ON_AUTO = 846,
    /** 手动中 */
    WAR_ON_HANG = 847,
    /** 攻击 */
    WAR_POSITION_1 = 848,
    /** 治疗 */
    WAR_POSITION_10 = 849,
    /** 面杀伤 */
    WAR_POSITION_11 = 850,
    /** 防御 */
    WAR_POSITION_2 = 851,
    /** 控制 */
    WAR_POSITION_3 = 852,
    /** 恢复 */
    WAR_POSITION_4 = 853,
    /** 辅助 */
    WAR_POSITION_5 = 854,
    /** 反攻 */
    WAR_POSITION_6 = 855,
    /** 持续杀伤 */
    WAR_POSITION_7 = 856,
    /** 生存 */
    WAR_POSITION_8 = 857,
    /** 突击 */
    WAR_POSITION_9 = 858,
    /** 小兵 */
    WAR_SOLDIER = 859,
    /** 此战斗不能跳过 */
    WAR_STEP_FAL = 860,
    /** VIP2或君主20级可以跳过战斗 */
    WAR_STEP_TIPS = 861,
    /** 城墙 */
    WAR_WALL = 862,
    /** 召唤物 */
    WAR_ZHW = 863,
    /** 木材 */
    WOOD = 864,
    /** 木材不足 */
    WOOD_LESS = 865,
    /** 敌军部队数量<font color = #e9e9e6>%s<font> */
    WOR_ARMY_COU = 866,
    /** 今日可剿匪次数<font color = #e9e9e6>%s/%s</font> */
    WOR_ATT_COU = 867,
    /** 君主%s等级可以攻打 */
    WOR_ATT_TIPS = 868,
    /** 后排只能上阵远程武将 */
    WOR_BACK = 869,
    /** 需要更多的后排武将 */
    WOR_BACK_TIPS = 870,
    /** 领取失败 */
    WOR_BAT_GET_FAL = 871,
    /** 该城池处于免战状态，请于【10点~14点和15点~24点】进行攻击。 */
    WOR_BD_BHTS = 872,
    /** 都城 */
    WOR_BD_DC = 873,
    /** 郡城 */
    WOR_BD_JC = 874,
    /** 太守： */
    WOR_BD_TS = 875,
    /** 王城 */
    WOR_BD_WC = 876,
    /** 县城 */
    WOR_BD_XC = 877,
    /** 拜访对象已过期！ */
    WOR_BF_FAL = 878,
    /** 正在拜访中！ */
    WOR_BF_FAL1 = 879,
    /** 非势力范围城池，无法拜访！ */
    WOR_BF_FAL2 = 880,
    /** 拜帖不足，可进行活动或任务获取。 */
    WOR_BF_FAL3 = 881,
    /** 访武将正在拜访中 */
    WOR_BF_FAL4 = 882,
    /** 购买次数需要<font color = #e9e9e6>%s</font>元宝 */
    WOR_BUY_GOLD = 883,
    /** 城防军 */
    WOR_CFJ = 884,
    /** 采集加速 */
    WOR_CO_ACC = 885,
    /** 今日可收集次数<font color = #e9e9e6>%s/%s</font> */
    WOR_CO_COU = 886,
    /** 收集%s分钟后刷新 */
    WOR_CO_REF = 887,
    /** 拜访 */
    WOR_EVT_BF = 888,
    /** 采集 */
    WOR_EVT_CJ = 889,
    /** 该类型暂无可进行的事件 */
    WOR_EVT_FAL = 890,
    /** 采集完成 */
    WOR_EVT_FINS = 891,
    /** 部队前往 */
    WOR_EVT_GO = 892,
    /** 木材 */
    WOR_EVT_MC = 893,
    /** 马贼 */
    WOR_EVT_MZ = 894,
    /** 农田 */
    WOR_EVT_NT = 895,
    /** 逃兵 */
    WOR_EVT_PJ = 896,
    /** 强盗 */
    WOR_EVT_QD = 897,
    /** 收集 */
    WOR_EVT_SJ = 898,
    /** 铁矿 */
    WOR_EVT_TK = 899,
    /** 银矿 */
    WOR_EVT_YK = 900,
    /** 前排只能上阵近战武将 */
    WOR_FRONT = 901,
    /** 需要更多的前排武将 */
    WOR_FRONT_TIPS = 902,
    /** 今日可采集次数<font color = #e9e9e6>%s/%s</font> */
    WOR_GA_COU = 903,
    /** 采集%s分钟后刷新 */
    WOR_GA_REF = 904,
    /** 交战中 */
    WOR_GZ_JZZ = 905,
    /** 列队中 */
    WOR_GZ_LDZ = 906,
    /** %s士兵 */
    WOR_GZ_NUM = 907,
    /** 前往【%s】 */
    WOR_HE_GO = 908,
    /** 帮助说明 */
    WOR_HELP_TITLE = 909,
    /** 封王战【%s】后开启 */
    WOR_KING_TIPS = 910,
    /** 当前世界等级为%s级，世界等级随着等级排名前100名玩家的平均等级变化。 */
    WOR_LEVEL_TIPS = 911,
    /** %s级解锁 */
    WOR_LOCK = 912,
    /** 太守%s */
    WOR_PRE_NAME = 913,
    /** 太守 无 */
    WOR_PRE_NONE = 914,
    /** 资源采集中 */
    WOR_RES_COLL = 915,
    /** 士兵不足，请前往招募界面招募士兵后再试。 */
    WOR_SOR_FAL = 916,
    /** <font color=#ff0000>兵力不足</font> */
    WOR_SOR_FAL1 = 917,
    /** 等级%s开启 */
    WOR_SOR_OPEN = 918,
    /** 补兵 */
    WOR_SUPP = 919,
    /** 一键补兵 */
    WOR_SUPP_ALL = 920,
    /** 补兵失败 */
    WOR_SUPP_FAL = 921,
    /** 国战中不能补兵 */
    WOR_SUPP_FAL1 = 922,
    /** %s库存不足 */
    WOR_SUPP_FAL2 = 923,
    /** 1、兵种克制可造成120%伤害，刀兵克制枪兵，枪兵克制骑兵，骑兵克制刀兵。\n\n2、城墙克制所有士兵单位，投石车克制城墙。 */
    WOR_SUPP_HELP_DESC = 924,
    /** 补兵成功 */
    WOR_SUPP_SUC = 925,
    /** 部队正在前往%s进行采集 */
    WOR_TEAM_ACT_CJ = 926,
    /** 已经有部队正在操作！ */
    WOR_TEAM_ACT_FAL = 927,
    /** 部队正在前往%s进行收集 */
    WOR_TEAM_ACT_SJ = 928,
    /** 当前目标已经派送部队前往 */
    WOR_TEAM_ACT_TIPS = 929,
    /** 部队正在前往%s进行剿匪 */
    WOR_TEAM_ACT_ZF = 930,
    /** 采集中 */
    WOR_TEAM_CJ = 931,
    /** 队伍未编队 */
    WOR_TEAM_EMPTY = 932,
    /** 国战部队 */
    WOR_TEAM_GZBD = 933,
    /** 排队中 */
    WOR_TEAM_GZPD = 934,
    /** 国战中 */
    WOR_TEAM_GZZD = 935,
    /** 剿匪中 */
    WOR_TEAM_JF = 936,
    /** 达到君主%s级或VIP%s级解锁下一个队伍 */
    WOR_TEAM_JSTS = 937,
    /** 提升VIP%s等级解锁下一个队伍 */
    WOR_TEAM_JSTS1 = 938,
    /** 达到君主%s级解锁下一个队伍 */
    WOR_TEAM_JSTS2 = 939,
    /** 空闲中 */
    WOR_TEAM_KX = 940,
    /** %s队 */
    WOR_TEAM_NUM = 941,
    /** 收集中 */
    WOR_TEAM_SJ = 942,
    /** <font color = #8A8A9E>%s</font>空闲中 */
    WOR_TEAM_TIPS = 943,
    /** 行军中 */
    WOR_TEAM_XJ = 944,
    /** 移动中 */
    WOR_TEAM_YD = 945,
    /** 是否前往兵营进行征兵 */
    WOR_TEAM_ZB = 946,
    /** 恭喜领取决战奖励 */
    WOR_TIPS_JZJL = 947,
    /** 请选择出征武将 */
    WOR_TMOVE_FAL = 948,
    /** 部队总兵力不足30%，请补兵后再进行操作 */
    WOR_TMOVE_FAL1 = 949,
    /** 部队在同一个城市 */
    WOR_TMOVE_FAL2 = 950,
    /** 寻找的路线为空 */
    WOR_TMOVE_FAL3 = 951,
    /** 英雄所在的城池没有道路通往该城池 */
    WOR_TMOVE_FAL4 = 952,
    /** 归师勿掩,穷寇勿追 */
    WOR_TMOVE_FAL5 = 953,
    /** 剩余时间少于10秒，不能使用加速道具 */
    WOR_TMOVE_SP_FAL = 954,
    /** 加速成功 */
    WOR_TMOVE_SPEED = 955,
    /** <font color = #ffff99>%s</font>后到达战场 */
    WOR_TMOVE_TIPS = 956,
    /** 拜访刷新 */
    WOR_VIS_RE = 957,
    /** 即将开放，敬请期待。 */
    WOR_XRZJS = 958,
    /** 精炼 */
    WROUGH = 959,
    /** 招募令 */
    ZML = 960,
    /** 招募令不足 */
    ZML_LESS = 961,
    /** 您已经解锁了限时礼包，有大量珍宝道具等着您！ */
    XSLB_TIP = 962,
    /** 黄巾军将攻打超过7个城池的国家 */
    AC_BAR_LIMIT = 963,
    /** 是否花费<font color = #e9e9e9>%s</font>元宝进行取代盟主 */
    GUILD_TIPS_TK = 964,
    /** 还没有达到盟主离线的弹劾时间。 */
    GUILD_TIPS_TK_TIME = 965,
    /** 守卫NPC部队每<font color=#ffff99>%s</font>分钟恢复<font color=#ffff99>%s</font>队 */
    WOR_TROOP_TIPS = 966,
    /** 累计伤害奖励 */
    BOSS_BOX_AWARD = 967,
    /** 缘分 */
    FATE_GEN_TITLE = 968,
    /** 联盟信息 */
    LEGION_CHECK_INFO = 969,
    /** 武将详情 */
    GENERAL_CHECK_INFO = 970,
    /** 黄巾军 */
    STATE_HUANG_TROOP = 971,
    /** 激活 */
    FATE_GEN_ACTIVE = 972,
    /** 下一级全体<font color=#ff0000>%s</font>星 */
    FATE_GEN_NEXT = 973,
    /** <font color=#e7c772>【%s】</font>%s */
    FATE_TEAM_TIPS1 = 974,
    /** <font color=#666666>【%s】%s</font> */
    FATE_TEAM_TIPS2 = 975,
    /** 全体<font color=#ff0000>%s</font>星 */
    FATE_GEN_ALL = 976,
    /** 确定回收 */
    GEN_DECOMOSE_SUR = 977,
    /** 重生 */
    REBIRTH = 978,
    /** 城池 */
    STATE_CITY = 979,
    /** 规模 */
    STATE_SCALE = 980,
    /** 掌权 */
    STATE_POWER = 981,
    /** 所属联盟 */
    STATE_LION = 982,
    /** 世界部队已上阵武将不可重生 */
    REBIRTH_WORLD_BATTLE = 983,
    /** 竞技场已上阵武将不可重生 */
    REBIRTH_APK_BATTLE = 984,
    /** 内政部队已上阵武将不可重生 */
    REBIRTH_PVE_BATTLE = 985,
    /** 该武将是红色品质，是否确定重生？ */
    REBIRTH_SUR_REDGEM = 986,
    /** 个人排名奖 */
    PLAYER_RANK_REWARD = 987,
    /** 国家排名奖 */
    COUNTRY_RANK_REWARD = 988,
    /** 个人挑战奖 */
    PLAYER_BATTLE_REWARD = 989,
    /** 襄阳战奖励 */
    XIANGYANG_RANK_TITLE = 990,
    /** 活动结束时，拥有襄阳城的国家直接获得襄阳战的胜利 */
    XIANGYANG_DETAILS_TITLE = 991,
    /** <font size=24>距离直接占领襄阳城剩余：</font><font color=#FFFF99 size=24>%s</font> */
    XIANGYANG_CAPTURE_LEFT = 992,
    /** 襄阳战正在交战中 */
    XIANGYANG_FIGHTING = 993,
    /** 查看详情 */
    XIANGYANG_SEE_DETAILS = 994,
    /** 每个国家排行前20的玩家可获得国家排名奖励 */
    XIANGYANG_COUNTRY_REWARD = 995,
    /** 襄阳战 */
    XIANGYANG_TITLE = 996,
    /** 胜利国全国每次奖励 */
    XIANGYANG_WIN_TITLE = 997,
    /** 称帝特权 */
    XIANGYANG_PRIVILEGE = 998,
    /** 奖励内容 */
    XIANGYANG_EFFECT = 999,
    /** 主城雕像供玩家膜拜\n每日获得帝王奖励 */
    XIANGYANG_PRIVILEGE_DES = 1000,
    /** 元宝\n绝世经验书\n升阶石\n银两 */
    XIANGYANG_EFFECT_DES = 1001,
    /** <font color=#00ff00>+300</font>\n<font color=#00ff00>+5</font>\n<font color=#00ff00>+200</font>\n<font color=#00ff00>+100万</font> */
    XIANGYANG_EFFECT_NUM = 1002,
    /** <font color=#ffefce size=24>距离开战还剩</font><font color=#ffff99 size=24>%s</font> */
    XIANGYANG_FIGHT_TIME = 1003,
    /** 1.襄阳战每七天开启一次，20点至21点为准备时间，21点至23点为开战时间。\n\n2.玩家在襄阳战地图创建部队或者将世界地图的部队移动到出生城后，对应的部队即可参战。\n\n3.襄阳战结束时，拥有襄阳城的国家战功第一玩家获得帝位，如果襄阳城没有被攻下，则战功最高玩家获得帝位。\n\n4.襄阳战结束前5分钟将不能再调动部队。 */
    XIANGYANG_DES = 1004,
    /** 报名 */
    JOIN = 1005,
    /** <font color=#aac7ff>膜拜人数：</font><font color=#ffff99> %d</font> */
    WORSHIP_NUM = 1006,
    /** <font color=#ABB7D1>襄阳战中</font><font color=#e7d772>获得帝位</font><font color=#ABB7D1>的玩家将每天被万民膜拜</font> */
    WORSHIP_DES = 1007,
    /** <font color=#abb7d1 size=20>杀敌数  </font><font color=#ffff99 size=20>%d</font> */
    XIANGYANG_KILL = 1008,
    /** 1.在位期间获得主城雕像供玩家膜拜。\n\n2.在位期间每日可获得帝王奖励，奖励通过邮件发放。\n\n3.上线后有全服系统公告。 */
    XIANGYANG_PRIVILEGE_TXT = 1009,
    /** 恭喜<font color=#e7c772>%s</font>成为皇帝 */
    XIANGYANG_EMPEROR_TIPS = 1010,
    /** 皇帝：<font color=#44d0f3>%s</font> */
    XIANGYANG_EMPEROR_NAME = 1011,
    /** 您已成功报名 */
    XIANGYANG_JOIN = 1012,
    /** 需要%s级才能报名 */
    XIANGYANG_JOIN_LEVEL = 1013,
    /** 襄阳战还在准备期，请先把部队派往出生城。 */
    XIANGYANG_FIGHT_TIPS = 1014,
    /** 幸运寻宝 */
    TURNTABLE = 1015,
    /** 襄阳城 */
    XIANGYANG_CITY = 1016,
    /** <font color=#ABB7D1>额外奖励累计</font><font color=#ffff99> %d</font>次 */
    TURNTABLE_OTHER_PIRCE = 1017,
    /** 已报名 */
    JOIN_DONE = 1018,
    /** <font size=24>距离襄阳城开战剩余：</font><font color=#FFFF99 size=24>%s</font> */
    XIANGYANG_BATTLE_LEFT = 1019,
    /** 当前战局 */
    XIANGYANG_TAP_CUR = 1020,
    /** 概率掉落 */
    BOSS_DROP = 1021,
    /** %s不足。 */
    FATE_STAR_TIP = 1022,
    /** 没有可解锁城池！ */
    WOR_LOCK_FIND_FAL = 1023,
    /** 战斗场次 */
    FIGHT_COUNT = 1024,
    /** <font color=#aac7ff>建筑等级</font><font color=#e7c772>%s</font> */
    CITY_BUILD_LEVEL = 1025,
    /** 建设度 */
    CITY_BUILD_EXP = 1026,
    /** 城市建筑 */
    CITY_BUILD_TITLE = 1027,
    /** 主公，您的建造已完成！ */
    CITY_BUILD_DONE = 1028,
    /** 提示：建筑等级越高，建筑武将获得经验越多。 */
    CITY_BUILD_TIPS = 1029,
    /** 建设中 */
    CITY_BUILD_ING = 1030,
    /** 达到战功商城上限之后不再获得战功商城货币，每天凌晨<font color=#e9e9e9>%s</font>点重置，君主<font color=#e9e9e9>%s</font>级提升上限。 */
    WOR_TIPS_MILITORY = 1031,
    /** 战功货币:<font color=#e9e9e9>%s</font> */
    WOR_MILITORY_COIN = 1032,
    /** 拜访  */
    NEW_GEN_BF = 1033,
    /** 限购 */
    NEW_GEN_XG = 1034,
    /** 详情 */
    NEW_GEN_XQ = 1035,
    /** 选择奖励 */
    NEW_GEN_GHJL = 1036,
    /**  拜访消耗信物 <font color=#FF0202>%d</font>/%d */
    NEW_GEN_XHXW = 1037,
    /** 每充值<font color=#feee3b>%d个元宝</font><font color=#ffffff>可获得一个信物</font>  */
    NEW_GEN_CZXW = 1038,
    /** 请选择自选奖励 */
    NEW_GEN_SEL_TIP = 1039,
    /** 信物不足 */
    NEW_GEN_XWBZ = 1040,
    /** <font color=#ffffff>%s</font><font color=#fff6c7>天</font><font color=#ffffff>%s</font><font color=#fff6c7>时</font><font color=#ffffff>%s</font><font color=#fff6c7>分</font>  */
    ACT_DJS = 1041,
    /** 奖励 */
    REWARD = 1042,
    /** 经验+<font color=#00ff00>%s</font> */
    CITY_BUILD_GEXP = 1043,
    /** 战功+<font color=#00ff00>%s</font> */
    CITY_BUILD_MILL = 1044,
    /** 建设度+<font color=#00ff00>%s</font> */
    CITY_BUILD_BEXP = 1045,
    /** 技能：<font color=#00ff00>%s</font> */
    CITY_BUILD_SKILL = 1046,
    /** 经验： */
    CITY_BUILD_SEXP = 1047,
    /** 刷新次数不足 */
    SEVENII_SHOP = 1048,
    /** 提升城池建造等级，获得补兵特权才能补兵 */
    CITY_BUILD_TIPS1 = 1049,
    /** 武馆 */
    WOR_EVT_MESUME = 1050,
    /** 隐士 */
    WOR_EVT_HERMIT = 1051,
    /** 玉石不足 */
    YU_LESS = 1052,
    /** 玉石不足，是否前往充值界面购买 */
    YU_LESS_TIPS = 1053,
    /** 请先通关前置关卡 */
    MAIN_HIS_TIPS = 1054,
    /** 幸运值越高越容易获得<font color=#e7c772>稀有物品</font> */
    TURNTABLE_TIP = 1055,
    /** 是否花费[img]icon_source_jade_png[/img]<font color = #e9e9e6>%s玉石</font>购买基金礼包？ */
    GROW_BUY_GIFT_TIPS = 1056,
    /** 是否花费[img]icon_source_jade_png[/img]<font color = #e9e9e6>%s玉石</font>续费购买？ */
    GROW_BUY_CARD_TIPS = 1057,
    /** 1.每次招募必定获得武将升级经验书。\n\n2.每招募10次必出整将。 */
    TAVEN_TIPS = 1058,
    /** 战役部队 */
    CAMP_HISTORY = 1059,
    /** 建筑情报 */
    BUILD_INFO = 1060,
    /** %s月%s日%s:%s */
    DATE = 1061,
    /** <font color=#e7c772>胜利！</font><font color=#abb7d1>我军于</font>%s<font color=#abb7d1>顺利攻克</font><font color=%s>%s</font></font><font color=#abb7d1>军</font><font color=#ffff5e>%s</font> */
    CITY_CHANGE_SUC = 1062,
    /** <font color=#abb7d1>非常遗憾！我军</font><font color=#ffff5e>%s</font><font color=#abb7d1>于</font>%s<font color=#abb7d1>被</font><font color=%s>%s</font><font color=#abb7d1>军占领！</font> */
    CITY_CHANGE_FALL = 1063,
    /** 建造已完成 */
    CITY_BUILD_DONE2 = 1064,
    /** 后完成建造 */
    CITY_BUILD_ING2 = 1065,
    /** 各城在<font color=#e9e9e9>23</font>点给太守所属联盟成员交税 */
    STATE_AWARD_TIPS = 1067,
    /** <font color=#FFFFFF>每天5点刷新免费次数  每次招募可以获得额外的经验书奖励</font> */
    TAVEN_TIPS_EW2 = 1068,
    /** VIP%s可创建联盟 */
    GUILD_CREATE_VIP = 1069,
    /** <font color=#e7c772>VIP%s</font>[img]icon_source_gold_png[/img]<font color=#ffffff>%s</font> */
    GUILD_CREATE_VIP2 = 1070,
    /** 跨服部队 */
    CROSS_TEAM_KFBD = 1071,
    /** 战争沙盘 */
    CROSS_SAND_TABLE = 1072,
    /** 沙盘规则介绍：\n\n1.在跨服战中，获胜方将取得沙盘中城池的占领资格。\n\n2.点击每级城池可查看占领方可获得的奖励内容。\n\n3.每次跨服战，获胜方服务器将在下次战斗中争夺更高级城池的占领资格。\n\n4.当获得占领皇城资格后，下一次活动则与其他占领皇城的区服进行王者间的卫冕之战，胜者继续占领皇城。\n\n5.在所有等级的城池争夺中，失败方将失去占领资格，下次跨服战从县城一级重新争夺。 */
    CROSS_SAND_TABLE_RULE = 1073,
    /** 剩余： */
    CROSS_TEAM_TIPS1 = 1074,
    /** 皇城 */
    WOR_BD_HC = 1075,
    /** 州城 */
    WOR_BD_ZC = 1076,
    /** 城池等级 */
    CAPTURE_ZONE = 1077,
    /** 皇帝奖励 */
    EMPEROR_REWARD = 1078,
    /** 全服奖励 */
    ALL_SERVER_REWARD = 1079,
    /** 每日奖励 */
    DAY_REWARD = 1080,
    /** 城市等级： */
    CROSS_CITY_LEVEL = 1081,
    /** 占领方： */
    CROSS_CAPTURE_ZONE = 1082,
    /** 统帅 */
    CROSS_JOB_KING = 1083,
    /** 左军大将 */
    CROSS_JOB_L = 1084,
    /** 中军大将 */
    CROSS_JOB_M = 1085,
    /** 右军大将 */
    CROSS_JOB_R = 1086,
    /** 敬请期待 */
    CROSS_TIPS1 = 1087,
    /** %s服 精英部队 %s */
    CROSS_KING_TROOP = 1088,
    /** 统领%s支部队 */
    CROSS_GEN_TROOP = 1089,
    /** %s级城池 */
    CROSS_CITY_LEVLE1 = 1090,
    /** 查看沙盘 */
    CROSS_SAND_VIEW = 1091,
    /** 跨服战规则\n\n1.开服已满15天且已在襄阳战中产生皇帝的服务器可参与下一次跨服战。\n2.开战当天早上5:00开始报名，已产生皇帝的服将自动报名。\n3.报名后，系统会根据各服实力匹配各自的对阵服。\n4.皇帝玩家和三国国君有军团操控特权，可控制一支本服的军团部队参战。\n5.跨服战中，优先攻破城门进入内城的服，可优先占领城内区域。\n6.跨服战结束时，占领城内区域多的一方服务器获胜，可晋级争夺更高级城池。\n7.每级城池争夺战获胜可获取丰厚奖励，占领皇城的服务器将获得跨服称王成就。 */
    CROSS_BZWD = 1092,
    /** 进入战场 */
    CROSS_ENTER_WAR = 1093,
    /** 战场BUFF */
    CROSS_BUFF_TITLE = 1094,
    /** <font color=#add7d1>强力</font><font color=#e7c772>BUFF</font><font color=#add7d1>加持，战场所向披靡！</font> */
    CROSS_BUFF_DESC = 1095,
    /** <font color=#add7d1>个人所有参战部队，</font><font color=#e7c772>%s</font><font color=#00ff00>+%s</font> */
    CROSS_BUFF_EFFECT1 = 1096,
    /** <font color=#add7d1>本服所有参战部队，</font><font color=#e7c772>%s</font><font color=#00ff00>+%s</font> */
    CROSS_BUFF_EFFECT2 = 1097,
    /** 【%s】%s<font color=#aac7ff>的军团，当前状态：</font>%s */
    CROSS_LEGION_ARMY = 1098,
    /** 个人排名奖励 */
    CROSS_RANK_GR = 1099,
    /** 联盟荣誉排名 */
    CROSS_RANK_JT = 1100,
    /** 荣誉累计奖励 */
    CROSS_RANK_RY = 1101,
    /** 占领区域：%s个 */
    CROSS_SITU_OCCU = 1102,
    /** 建造箭塔：%s个 */
    CROSS_SITU_TOWER = 1103,
    /** 当前部队：%s */
    CROSS_SITU_TEAM = 1104,
    /** 剩余兵力：%s */
    CROSS_SITU_SUR = 1105,
    /** %s <font color=#e9e9e9>(%s级城池)</font> */
    CROSS_CITY_NAME = 1106,
    /** 你不是军团长  */
    CROSS_LEGION_NO = 1107,
    /** 未解锁 */
    CROSS_TEAM_LOCK = 1108,
    /** 精彩国战 */
    WORLD_NOTICE_TITLE = 1109,
    /** 国战说明 */
    WORLD_NOTICE_DESC = 1110,
    /** 逐鹿天下 */
    WORLD_NOTICE_FIGHT = 1111,
    /** 国战简介 */
    WOR_EXPLAIN_BRIEF = 1112,
    /** 占领城池 */
    WOR_EXPLAIN_OCC = 1113,
    /** 补兵规则 */
    WOR_EXPLAIN_TROOP = 1114,
    /** 集结攻城 */
    WOR_EXPLAIN_AGG = 1115,
    /** 黄巾入侵 */
    WOR_EXPLAIN_YELLOW = 1116,
    /** 加官进爵 */
    WOR_EXPLAIN_OFFICE = 1117,
    /** 复制成功 */
    SERVICE_WND = 1118,
    /** 每日惊喜商城 */
    SHOP_DAILY_SURPRISE = 1119,
    /** 主公等级<font color=#FFFF99>%s</font>级开启国战 */
    WOR_OPEN_LEV = 1120,
    /** 补兵规则说明\n\n1.在世界国战中，武将所携带的兵力会在战斗中损耗。\n2.当武将兵力消耗殆尽时将无法继续战斗，会自动退出战场并回到出生城池。\n3.部队只有在己方占领的城池中才可补兵，战斗中和行军途中不可补兵。\n4.激活对应兵种兵营后，可在部队界面中招募兵力并储存到兵库。\n5.补兵需消耗兵库兵力，升级对应兵种的兵营提升兵库的存兵上限。\n6.内政部队在进行关卡和副本等战斗任务中不消耗兵力。 */
    WOR_DESC1 = 1121,
    /** 加官进爵说明\n\n1.在参与国战时可获得大量战功，当战功达到条件即可晋升官职获得特权。\n2.每个国家有多个官职，同时满足条件时按战功高者获得官职。\n3.官职每半小时变动一次，按实时战功排名安排新的官员。\n4.在封王战中，当王城被攻克时战功最高者获得王位成为国王。\n5.每个官职都有对应的俸禄，在每天21点发放。\n6.国王三天不上线可被官员弹劾，弹劾成功后由发起弹劾者继任国王。 */
    WOR_DESC2 = 1122,
    /** 消耗%s点积分可进行积分召唤，必出<font color=#FF0000>红色武将</font> */
    TAVEN_SAFETY_TIP = 1123,
    /** 召唤 */
    TAVEN_SAFETY_BTN = 1124,
    /** 积分召唤 */
    TAVEN_SAFETY_CALL = 1125,
    /** <font color=#ffffff size=28>%s</font><font color=#abb7d1>时</font><font color=#ffffff size=28>%s</font><font color=#abb7d1>分</font><font color=#ffffff size=28>%s</font><font color=#abb7d1>秒</font>  */
    ACT_SFM = 1126,
    /** 跨服战场 */
    CROSS_WAR_TITLE = 1127,
    /** 荣誉商城 */
    HONOR_SHOP = 1128,
    /** 荣誉不足 */
    HONOR_LESS = 1129,
    /** <font color=#ffffff >%s</font>月<font color=#ffffff >%s</font>日<font color=#ffffff >%s:%s</font> */
    DATE_COLOR = 1130,
    /** V%s可使用 */
    HEIGHT_VIP_BUY = 1131,
    /** VIP%s可激活元宝购买 */
    HEIGHT_VIP_BUY_D = 1132,
}

